#!/usr/bin/env python3
# Prototype: generate Matter cluster/command/attribute name tables for the
# dissector from the connectedhomeip data-model XML for a given spec version.
#
#   make-matter-clusters.py <data_model/clusters dir> <cluster_ids.json> > packet-matter-clusters.c
import sys, os, json, glob, re
import xml.etree.ElementTree as ET

clusters_dir, ids_json = sys.argv[1], sys.argv[2]
ids = {int(k): v for k, v in json.load(open(ids_json)).items()}

# Clusters from earlier specification releases that are absent from this
# data model but may still appear in captures of older devices.
LEGACY_CLUSTERS = {
    0x0005: "Scenes",
    0x0301: "Ballast Configuration",
}
for _cid, _name in LEGACY_CLUSTERS.items():
    ids.setdefault(_cid, _name)

def c_ident(cid): return f"0x{cid:04X}"

# Per cluster: {cid: {'cmds': {id:name}, 'attrs': {id:name}}}
members = {}
for f in sorted(glob.glob(os.path.join(clusters_dir, "*.xml"))):
    try:
        root = ET.parse(f).getroot()
    except ET.ParseError:
        continue
    # A file may list one or more cluster IDs (aliased/derived clusters);
    # apply its attributes and commands to each.
    cid_els = root.findall("clusterIds/clusterId") + root.findall("clusterId")
    cids = []
    for e in cid_els:
        if e.get("id"):
            try:
                cids.append(int(e.get("id"), 16))
            except ValueError:
                pass
    if not cids:
        continue
    attrs, cmds, rsps = {}, {}, {}
    for a in root.findall("attributes/attribute"):
        aid, name = a.get("id"), a.get("name")
        if aid and name:
            attrs.setdefault(int(aid, 16), name)
    for c in root.findall("commands/command"):
        cidn, name, direction = c.get("id"), c.get("name"), c.get("direction", "")
        if not (cidn and name):
            continue
        if direction == "commandToServer":
            cmds.setdefault(int(cidn, 16), name)      # client -> server (request)
        elif direction == "responseFromServer":
            rsps.setdefault(int(cidn, 16), name)      # server -> client (response)
    for cid in cids:
        m = members.setdefault(cid, {"cmds": {}, "rsps": {}, "attrs": {}})
        m["attrs"].update(attrs)
        m["cmds"].update(cmds)
        m["rsps"].update(rsps)

def esc(s): return s.replace('"', '\\"')

out = []
out.append("/* Generated by tools/make-matter-clusters.py from the Matter 1.6.1 data model. */")
out.append("/* Do not edit. */\n")
out.append("#include \"config.h\"")
out.append("#include <wsutil/value_string.h>")
out.append("#include <wsutil/array.h>")
out.append("#include \"packet-matter-clusters.h\"\n")

# Cluster ID names
out.append("const value_string matter_cluster_id_vals[] = {")
for cid in sorted(ids):
    out.append(f'    {{ {c_ident(cid)}, "{esc(ids[cid])}" }},')
out.append("    { 0, NULL }\n};\n")

# Per-cluster command/attribute value_strings
have = sorted(c for c in members if members[c]["cmds"] or members[c]["rsps"] or members[c]["attrs"])
for cid in have:
    m = members[cid]
    if m["cmds"]:
        out.append(f"static const value_string matter_cmd_{cid:04x}_vals[] = {{")
        for i in sorted(m["cmds"]):
            out.append(f'    {{ 0x{i:02X}, "{esc(m["cmds"][i])}" }},')
        out.append("    { 0, NULL }\n};")
    if m["rsps"]:
        out.append(f"static const value_string matter_rsp_{cid:04x}_vals[] = {{")
        for i in sorted(m["rsps"]):
            out.append(f'    {{ 0x{i:02X}, "{esc(m["rsps"][i])}" }},')
        out.append("    { 0, NULL }\n};")
    if m["attrs"]:
        out.append(f"static const value_string matter_attr_{cid:04x}_vals[] = {{")
        for i in sorted(m["attrs"]):
            out.append(f'    {{ 0x{i:04X}, "{esc(m["attrs"][i])}" }},')
        out.append("    { 0, NULL }\n};")

out.append("\ntypedef struct { uint32_t cluster_id; const value_string *cmds; const value_string *rsps; const value_string *attrs; } matter_cluster_members_t;\n")
out.append("static const matter_cluster_members_t matter_cluster_members[] = {")
for cid in have:
    m = members[cid]
    cn = f"matter_cmd_{cid:04x}_vals" if m["cmds"] else "NULL"
    rn = f"matter_rsp_{cid:04x}_vals" if m["rsps"] else "NULL"
    an = f"matter_attr_{cid:04x}_vals" if m["attrs"] else "NULL"
    out.append(f"    {{ {c_ident(cid)}, {cn}, {rn}, {an} }},")
out.append("};\n")

out.append("""static const matter_cluster_members_t *
matter_cluster_lookup(uint32_t cluster_id)
{
    for (unsigned i = 0; i < array_length(matter_cluster_members); i++)
        if (matter_cluster_members[i].cluster_id == cluster_id)
            return &matter_cluster_members[i];
    return NULL;
}

const char *
matter_cluster_attribute_name(uint32_t cluster_id, uint32_t id)
{
    const matter_cluster_members_t *m = matter_cluster_lookup(cluster_id);
    return (m && m->attrs) ? try_val_to_str(id, m->attrs) : NULL;
}

const char *
matter_cluster_command_name(uint32_t cluster_id, uint32_t id, bool is_response)
{
    const matter_cluster_members_t *m = matter_cluster_lookup(cluster_id);
    if (!m)
        return NULL;
    const value_string *vs = is_response ? m->rsps : m->cmds;
    return vs ? try_val_to_str(id, vs) : NULL;
}""")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write(f"clusters with members: {len(have)}; attrs: "
                 f"{sum(len(members[c]['attrs']) for c in have)}; "
                 f"cmds: {sum(len(members[c]['cmds']) for c in have)}; "
                 f"rsps: {sum(len(members[c]['rsps']) for c in have)}\n")
