/* Generated by tools/make-matter-clusters.py from the Matter 1.6.1 data model. */
/* Do not edit. */

#include "config.h"
#include <wsutil/value_string.h>
#include <wsutil/array.h>
#include "packet-matter-clusters.h"

const value_string matter_cluster_id_vals[] = {
    { 0x0003, "Identify" },
    { 0x0004, "Groups" },
    { 0x0005, "Scenes" },
    { 0x0006, "On/Off" },
    { 0x0008, "Level Control" },
    { 0x001D, "Descriptor" },
    { 0x001E, "Binding" },
    { 0x001F, "Access Control" },
    { 0x0025, "Actions" },
    { 0x0028, "Basic Information" },
    { 0x0029, "OTA Software Update Provider" },
    { 0x002A, "OTA Software Update Requestor" },
    { 0x002B, "Localization Configuration" },
    { 0x002C, "Time Format Localization" },
    { 0x002D, "Unit Localization" },
    { 0x002E, "Power Source Configuration" },
    { 0x002F, "Power Source" },
    { 0x0030, "General Commissioning" },
    { 0x0031, "Network Commissioning" },
    { 0x0032, "Diagnostic Logs" },
    { 0x0033, "General Diagnostics" },
    { 0x0034, "Software Diagnostics" },
    { 0x0035, "Thread Network Diagnostics" },
    { 0x0036, "Wi-Fi Network Diagnostics" },
    { 0x0037, "Ethernet Network Diagnostics" },
    { 0x0038, "Time Synchronization" },
    { 0x0039, "Bridged Device Basic Information" },
    { 0x003B, "Switch" },
    { 0x003C, "Administrator Commissioning" },
    { 0x003E, "Operational Credentials" },
    { 0x003F, "Group Key Management" },
    { 0x0040, "Fixed Label" },
    { 0x0041, "User Label" },
    { 0x0045, "Boolean State" },
    { 0x0046, "ICD Management" },
    { 0x0048, "Oven Cavity Operational State" },
    { 0x0049, "Oven Mode" },
    { 0x004A, "Laundry Dryer Controls" },
    { 0x0050, "Mode Select" },
    { 0x0051, "Laundry Washer Mode" },
    { 0x0052, "Refrigerator And Temperature Controlled Cabinet Mode" },
    { 0x0053, "Laundry Washer Controls" },
    { 0x0054, "RVC Run Mode" },
    { 0x0055, "RVC Clean Mode" },
    { 0x0056, "Temperature Control" },
    { 0x0057, "Refrigerator Alarm" },
    { 0x0059, "Dishwasher Mode" },
    { 0x005B, "Air Quality" },
    { 0x005C, "Smoke CO Alarm" },
    { 0x005D, "Dishwasher Alarm" },
    { 0x005E, "Microwave Oven Mode" },
    { 0x005F, "Microwave Oven Control" },
    { 0x0060, "Operational State" },
    { 0x0061, "RVC Operational State" },
    { 0x0062, "Scenes Management" },
    { 0x0064, "Temperature Alarm" },
    { 0x0065, "Groupcast" },
    { 0x0071, "HEPA Filter Monitoring" },
    { 0x0072, "Activated Carbon Filter Monitoring" },
    { 0x0079, "Water Tank Level Monitoring" },
    { 0x0080, "Boolean State Configuration" },
    { 0x0081, "Valve Configuration and Control" },
    { 0x0090, "Electrical Power Measurement" },
    { 0x0091, "Electrical Energy Measurement" },
    { 0x0094, "Water Heater Management" },
    { 0x0095, "Commodity Price" },
    { 0x0097, "Messages" },
    { 0x0098, "Device Energy Management" },
    { 0x0099, "Energy EVSE" },
    { 0x009B, "Energy Preference" },
    { 0x009C, "Power Topology" },
    { 0x009D, "Energy EVSE Mode" },
    { 0x009E, "Water Heater Mode" },
    { 0x009F, "Device Energy Management Mode" },
    { 0x00A0, "Electrical Grid Conditions" },
    { 0x0101, "Door Lock" },
    { 0x0102, "Window Covering" },
    { 0x0104, "Closure Control" },
    { 0x0105, "Closure Dimension" },
    { 0x0150, "Service Area" },
    { 0x0200, "Pump Configuration and Control" },
    { 0x0201, "Thermostat" },
    { 0x0202, "Fan Control" },
    { 0x0204, "Thermostat User Interface Configuration" },
    { 0x0300, "Color Control" },
    { 0x0301, "Ballast Configuration" },
    { 0x0400, "Illuminance Measurement" },
    { 0x0402, "Temperature Measurement" },
    { 0x0403, "Pressure Measurement" },
    { 0x0404, "Flow Measurement" },
    { 0x0405, "Relative Humidity Measurement" },
    { 0x0406, "Occupancy Sensing" },
    { 0x040C, "Carbon Monoxide Concentration Measurement" },
    { 0x040D, "Carbon Dioxide Concentration Measurement" },
    { 0x0413, "Nitrogen Dioxide Concentration Measurement" },
    { 0x0415, "Ozone Concentration Measurement" },
    { 0x042A, "PM2.5 Concentration Measurement" },
    { 0x042B, "Formaldehyde Concentration Measurement" },
    { 0x042C, "PM1 Concentration Measurement" },
    { 0x042D, "PM10 Concentration Measurement" },
    { 0x042E, "Total Volatile Organic Compounds Concentration Measurement" },
    { 0x042F, "Radon Concentration Measurement" },
    { 0x0430, "Soil Measurement" },
    { 0x0431, "Ambient Context Sensing" },
    { 0x0451, "Wi-Fi Network Management" },
    { 0x0452, "Thread Border Router Management" },
    { 0x0453, "Thread Network Directory" },
    { 0x0503, "Wake On LAN" },
    { 0x0504, "Channel" },
    { 0x0505, "Target Navigator" },
    { 0x0506, "Media Playback" },
    { 0x0507, "Media Input" },
    { 0x0508, "Low Power" },
    { 0x0509, "Keypad Input" },
    { 0x050A, "Content Launcher" },
    { 0x050B, "Audio Output" },
    { 0x050C, "Application Launcher" },
    { 0x050D, "Application Basic" },
    { 0x050E, "Account Login" },
    { 0x050F, "Content Control" },
    { 0x0510, "Content App Observer" },
    { 0x0550, "Zone Management" },
    { 0x0551, "Camera AV Stream Management" },
    { 0x0552, "Camera AV Settings User Level Management" },
    { 0x0553, "WebRTC Transport Provider" },
    { 0x0554, "WebRTC Transport Requestor" },
    { 0x0555, "Push AV Stream Transport" },
    { 0x0556, "Chime" },
    { 0x0700, "Commodity Tariff" },
    { 0x0750, "Ecosystem Information" },
    { 0x0751, "Commissioner Control" },
    { 0x0752, "Joint Fabric Datastore" },
    { 0x0753, "Joint Fabric Administrator" },
    { 0x0801, "TLS Certificate Management" },
    { 0x0802, "TLS Client Management" },
    { 0x0B06, "Meter Identification" },
    { 0x0B07, "Commodity Metering" },
    { 0, NULL }
};

static const value_string matter_cmd_0003_vals[] = {
    { 0x00, "Identify" },
    { 0x40, "TriggerEffect" },
    { 0, NULL }
};
static const value_string matter_attr_0003_vals[] = {
    { 0x0000, "IdentifyTime" },
    { 0x0001, "IdentifyType" },
    { 0, NULL }
};
static const value_string matter_cmd_0004_vals[] = {
    { 0x00, "AddGroup" },
    { 0x01, "ViewGroup" },
    { 0x02, "GetGroupMembership" },
    { 0x03, "RemoveGroup" },
    { 0x04, "RemoveAllGroups" },
    { 0x05, "AddGroupIfIdentifying" },
    { 0, NULL }
};
static const value_string matter_rsp_0004_vals[] = {
    { 0x00, "AddGroupResponse" },
    { 0x01, "ViewGroupResponse" },
    { 0x02, "GetGroupMembershipResponse" },
    { 0x03, "RemoveGroupResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0004_vals[] = {
    { 0x0000, "NameSupport" },
    { 0, NULL }
};
static const value_string matter_cmd_0006_vals[] = {
    { 0x00, "Off" },
    { 0x01, "On" },
    { 0x02, "Toggle" },
    { 0x40, "OffWithEffect" },
    { 0x41, "OnWithRecallGlobalScene" },
    { 0x42, "OnWithTimedOff" },
    { 0, NULL }
};
static const value_string matter_attr_0006_vals[] = {
    { 0x0000, "OnOff" },
    { 0x4000, "GlobalSceneControl" },
    { 0x4001, "OnTime" },
    { 0x4002, "OffWaitTime" },
    { 0x4003, "StartUpOnOff" },
    { 0, NULL }
};
static const value_string matter_cmd_0008_vals[] = {
    { 0x00, "MoveToLevel" },
    { 0x01, "Move" },
    { 0x02, "Step" },
    { 0x03, "Stop" },
    { 0x04, "MoveToLevelWithOnOff" },
    { 0x05, "MoveWithOnOff" },
    { 0x06, "StepWithOnOff" },
    { 0x07, "StopWithOnOff" },
    { 0x08, "MoveToClosestFrequency" },
    { 0, NULL }
};
static const value_string matter_attr_0008_vals[] = {
    { 0x0000, "CurrentLevel" },
    { 0x0001, "RemainingTime" },
    { 0x0002, "MinLevel" },
    { 0x0003, "MaxLevel" },
    { 0x0004, "CurrentFrequency" },
    { 0x0005, "MinFrequency" },
    { 0x0006, "MaxFrequency" },
    { 0x000F, "Options" },
    { 0x0010, "OnOffTransitionTime" },
    { 0x0011, "OnLevel" },
    { 0x0012, "OnTransitionTime" },
    { 0x0013, "OffTransitionTime" },
    { 0x0014, "DefaultMoveRate" },
    { 0x4000, "StartUpCurrentLevel" },
    { 0, NULL }
};
static const value_string matter_attr_001d_vals[] = {
    { 0x0000, "DeviceTypeList" },
    { 0x0001, "ServerList" },
    { 0x0002, "ClientList" },
    { 0x0003, "PartsList" },
    { 0x0004, "TagList" },
    { 0x0005, "EndpointUniqueID" },
    { 0, NULL }
};
static const value_string matter_attr_001e_vals[] = {
    { 0x0000, "Binding" },
    { 0, NULL }
};
static const value_string matter_cmd_001f_vals[] = {
    { 0x00, "ReviewFabricRestrictions" },
    { 0, NULL }
};
static const value_string matter_rsp_001f_vals[] = {
    { 0x01, "ReviewFabricRestrictionsResponse" },
    { 0, NULL }
};
static const value_string matter_attr_001f_vals[] = {
    { 0x0000, "ACL" },
    { 0x0001, "Extension" },
    { 0x0002, "SubjectsPerAccessControlEntry" },
    { 0x0003, "TargetsPerAccessControlEntry" },
    { 0x0004, "AccessControlEntriesPerFabric" },
    { 0x0005, "CommissioningARL" },
    { 0x0006, "ARL" },
    { 0x0007, "AuxiliaryACL" },
    { 0, NULL }
};
static const value_string matter_cmd_0025_vals[] = {
    { 0x00, "InstantAction" },
    { 0x01, "InstantActionWithTransition" },
    { 0x02, "StartAction" },
    { 0x03, "StartActionWithDuration" },
    { 0x04, "StopAction" },
    { 0x05, "PauseAction" },
    { 0x06, "PauseActionWithDuration" },
    { 0x07, "ResumeAction" },
    { 0x08, "EnableAction" },
    { 0x09, "EnableActionWithDuration" },
    { 0x0A, "DisableAction" },
    { 0x0B, "DisableActionWithDuration" },
    { 0, NULL }
};
static const value_string matter_attr_0025_vals[] = {
    { 0x0000, "ActionList" },
    { 0x0001, "EndpointLists" },
    { 0x0002, "SetupURL" },
    { 0, NULL }
};
static const value_string matter_attr_0028_vals[] = {
    { 0x0000, "DataModelRevision" },
    { 0x0001, "VendorName" },
    { 0x0002, "VendorID" },
    { 0x0003, "ProductName" },
    { 0x0004, "ProductID" },
    { 0x0005, "NodeLabel" },
    { 0x0006, "Location" },
    { 0x0007, "HardwareVersion" },
    { 0x0008, "HardwareVersionString" },
    { 0x0009, "SoftwareVersion" },
    { 0x000A, "SoftwareVersionString" },
    { 0x000B, "ManufacturingDate" },
    { 0x000C, "PartNumber" },
    { 0x000D, "ProductURL" },
    { 0x000E, "ProductLabel" },
    { 0x000F, "SerialNumber" },
    { 0x0010, "LocalConfigDisabled" },
    { 0x0011, "Reachable" },
    { 0x0012, "UniqueID" },
    { 0x0013, "CapabilityMinima" },
    { 0x0014, "ProductAppearance" },
    { 0x0015, "SpecificationVersion" },
    { 0x0016, "MaxPathsPerInvoke" },
    { 0x0018, "ConfigurationVersion" },
    { 0, NULL }
};
static const value_string matter_cmd_0029_vals[] = {
    { 0x00, "QueryImage" },
    { 0x02, "ApplyUpdateRequest" },
    { 0x04, "NotifyUpdateApplied" },
    { 0, NULL }
};
static const value_string matter_rsp_0029_vals[] = {
    { 0x01, "QueryImageResponse" },
    { 0x03, "ApplyUpdateResponse" },
    { 0, NULL }
};
static const value_string matter_cmd_002a_vals[] = {
    { 0x00, "AnnounceOTAProvider" },
    { 0, NULL }
};
static const value_string matter_attr_002a_vals[] = {
    { 0x0000, "DefaultOTAProviders" },
    { 0x0001, "UpdatePossible" },
    { 0x0002, "UpdateState" },
    { 0x0003, "UpdateStateProgress" },
    { 0, NULL }
};
static const value_string matter_attr_002b_vals[] = {
    { 0x0000, "ActiveLocale" },
    { 0x0001, "SupportedLocales" },
    { 0, NULL }
};
static const value_string matter_attr_002c_vals[] = {
    { 0x0000, "HourFormat" },
    { 0x0001, "ActiveCalendarType" },
    { 0x0002, "SupportedCalendarTypes" },
    { 0, NULL }
};
static const value_string matter_attr_002d_vals[] = {
    { 0x0000, "TemperatureUnit" },
    { 0x0001, "SupportedTemperatureUnits" },
    { 0, NULL }
};
static const value_string matter_attr_002e_vals[] = {
    { 0x0000, "Sources" },
    { 0, NULL }
};
static const value_string matter_attr_002f_vals[] = {
    { 0x0000, "Status" },
    { 0x0001, "Order" },
    { 0x0002, "Description" },
    { 0x0003, "WiredAssessedInputVoltage" },
    { 0x0004, "WiredAssessedInputFrequency" },
    { 0x0005, "WiredCurrentType" },
    { 0x0006, "WiredAssessedCurrent" },
    { 0x0007, "WiredNominalVoltage" },
    { 0x0008, "WiredMaximumCurrent" },
    { 0x0009, "WiredPresent" },
    { 0x000A, "ActiveWiredFaults" },
    { 0x000B, "BatVoltage" },
    { 0x000C, "BatPercentRemaining" },
    { 0x000D, "BatTimeRemaining" },
    { 0x000E, "BatChargeLevel" },
    { 0x000F, "BatReplacementNeeded" },
    { 0x0010, "BatReplaceability" },
    { 0x0011, "BatPresent" },
    { 0x0012, "ActiveBatFaults" },
    { 0x0013, "BatReplacementDescription" },
    { 0x0014, "BatCommonDesignation" },
    { 0x0015, "BatANSIDesignation" },
    { 0x0016, "BatIECDesignation" },
    { 0x0017, "BatApprovedChemistry" },
    { 0x0018, "BatCapacity" },
    { 0x0019, "BatQuantity" },
    { 0x001A, "BatChargeState" },
    { 0x001B, "BatTimeToFullCharge" },
    { 0x001C, "BatFunctionalWhileCharging" },
    { 0x001D, "BatChargingCurrent" },
    { 0x001E, "ActiveBatChargeFaults" },
    { 0x001F, "EndpointList" },
    { 0, NULL }
};
static const value_string matter_cmd_0030_vals[] = {
    { 0x00, "ArmFailSafe" },
    { 0x02, "SetRegulatoryConfig" },
    { 0x04, "CommissioningComplete" },
    { 0x06, "SetTCAcknowledgements" },
    { 0, NULL }
};
static const value_string matter_rsp_0030_vals[] = {
    { 0x01, "ArmFailSafeResponse" },
    { 0x03, "SetRegulatoryConfigResponse" },
    { 0x05, "CommissioningCompleteResponse" },
    { 0x07, "SetTCAcknowledgementsResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0030_vals[] = {
    { 0x0000, "Breadcrumb" },
    { 0x0001, "BasicCommissioningInfo" },
    { 0x0002, "RegulatoryConfig" },
    { 0x0003, "LocationCapability" },
    { 0x0004, "SupportsConcurrentConnection" },
    { 0x0005, "TCAcceptedVersion" },
    { 0x0006, "TCMinRequiredVersion" },
    { 0x0007, "TCAcknowledgements" },
    { 0x0008, "TCAcknowledgementsRequired" },
    { 0x0009, "TCUpdateDeadline" },
    { 0x000A, "RecoveryIdentifier" },
    { 0x000B, "NetworkRecoveryReason" },
    { 0x000C, "IsCommissioningWithoutPower" },
    { 0, NULL }
};
static const value_string matter_cmd_0031_vals[] = {
    { 0x00, "ScanNetworks" },
    { 0x02, "AddOrUpdateWiFiNetwork" },
    { 0x03, "AddOrUpdateThreadNetwork" },
    { 0x04, "RemoveNetwork" },
    { 0x06, "ConnectNetwork" },
    { 0x08, "ReorderNetwork" },
    { 0, NULL }
};
static const value_string matter_rsp_0031_vals[] = {
    { 0x01, "ScanNetworksResponse" },
    { 0x05, "NetworkConfigResponse" },
    { 0x07, "ConnectNetworkResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0031_vals[] = {
    { 0x0000, "MaxNetworks" },
    { 0x0001, "Networks" },
    { 0x0002, "ScanMaxTimeSeconds" },
    { 0x0003, "ConnectMaxTimeSeconds" },
    { 0x0004, "InterfaceEnabled" },
    { 0x0005, "LastNetworkingStatus" },
    { 0x0006, "LastNetworkID" },
    { 0x0007, "LastConnectErrorValue" },
    { 0x0008, "SupportedWiFiBands" },
    { 0x0009, "SupportedThreadFeatures" },
    { 0x000A, "ThreadVersion" },
    { 0, NULL }
};
static const value_string matter_cmd_0032_vals[] = {
    { 0x00, "RetrieveLogsRequest" },
    { 0, NULL }
};
static const value_string matter_rsp_0032_vals[] = {
    { 0x01, "RetrieveLogsResponse" },
    { 0, NULL }
};
static const value_string matter_cmd_0033_vals[] = {
    { 0x00, "TestEventTrigger" },
    { 0x01, "TimeSnapshot" },
    { 0x03, "PayloadTestRequest" },
    { 0, NULL }
};
static const value_string matter_rsp_0033_vals[] = {
    { 0x02, "TimeSnapshotResponse" },
    { 0x04, "PayloadTestResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0033_vals[] = {
    { 0x0000, "NetworkInterfaces" },
    { 0x0001, "RebootCount" },
    { 0x0002, "UpTime" },
    { 0x0003, "TotalOperationalHours" },
    { 0x0004, "BootReason" },
    { 0x0005, "ActiveHardwareFaults" },
    { 0x0006, "ActiveRadioFaults" },
    { 0x0007, "ActiveNetworkFaults" },
    { 0x0008, "TestEventTriggersEnabled" },
    { 0x0009, "DoNotUse" },
    { 0x000A, "DeviceLoadStatus" },
    { 0, NULL }
};
static const value_string matter_cmd_0034_vals[] = {
    { 0x00, "ResetWatermarks" },
    { 0, NULL }
};
static const value_string matter_attr_0034_vals[] = {
    { 0x0000, "ThreadMetrics" },
    { 0x0001, "CurrentHeapFree" },
    { 0x0002, "CurrentHeapUsed" },
    { 0x0003, "CurrentHeapHighWatermark" },
    { 0, NULL }
};
static const value_string matter_cmd_0035_vals[] = {
    { 0x00, "ResetCounts" },
    { 0, NULL }
};
static const value_string matter_attr_0035_vals[] = {
    { 0x0000, "Channel" },
    { 0x0001, "RoutingRole" },
    { 0x0002, "NetworkName" },
    { 0x0003, "PanId" },
    { 0x0004, "ExtendedPanId" },
    { 0x0005, "MeshLocalPrefix" },
    { 0x0006, "OverrunCount" },
    { 0x0007, "NeighborTable" },
    { 0x0008, "RouteTable" },
    { 0x0009, "PartitionId" },
    { 0x000A, "Weighting" },
    { 0x000B, "DataVersion" },
    { 0x000C, "StableDataVersion" },
    { 0x000D, "LeaderRouterId" },
    { 0x000E, "DetachedRoleCount" },
    { 0x000F, "ChildRoleCount" },
    { 0x0010, "RouterRoleCount" },
    { 0x0011, "LeaderRoleCount" },
    { 0x0012, "AttachAttemptCount" },
    { 0x0013, "PartitionIdChangeCount" },
    { 0x0014, "BetterPartitionAttachAttemptCount" },
    { 0x0015, "ParentChangeCount" },
    { 0x0016, "TxTotalCount" },
    { 0x0017, "TxUnicastCount" },
    { 0x0018, "TxBroadcastCount" },
    { 0x0019, "TxAckRequestedCount" },
    { 0x001A, "TxAckedCount" },
    { 0x001B, "TxNoAckRequestedCount" },
    { 0x001C, "TxDataCount" },
    { 0x001D, "TxDataPollCount" },
    { 0x001E, "TxBeaconCount" },
    { 0x001F, "TxBeaconRequestCount" },
    { 0x0020, "TxOtherCount" },
    { 0x0021, "TxRetryCount" },
    { 0x0022, "TxDirectMaxRetryExpiryCount" },
    { 0x0023, "TxIndirectMaxRetryExpiryCount" },
    { 0x0024, "TxErrCcaCount" },
    { 0x0025, "TxErrAbortCount" },
    { 0x0026, "TxErrBusyChannelCount" },
    { 0x0027, "RxTotalCount" },
    { 0x0028, "RxUnicastCount" },
    { 0x0029, "RxBroadcastCount" },
    { 0x002A, "RxDataCount" },
    { 0x002B, "RxDataPollCount" },
    { 0x002C, "RxBeaconCount" },
    { 0x002D, "RxBeaconRequestCount" },
    { 0x002E, "RxOtherCount" },
    { 0x002F, "RxAddressFilteredCount" },
    { 0x0030, "RxDestAddrFilteredCount" },
    { 0x0031, "RxDuplicatedCount" },
    { 0x0032, "RxErrNoFrameCount" },
    { 0x0033, "RxErrUnknownNeighborCount" },
    { 0x0034, "RxErrInvalidSrcAddrCount" },
    { 0x0035, "RxErrSecCount" },
    { 0x0036, "RxErrFcsCount" },
    { 0x0037, "RxErrOtherCount" },
    { 0x0038, "ActiveTimestamp" },
    { 0x0039, "PendingTimestamp" },
    { 0x003A, "Delay" },
    { 0x003B, "SecurityPolicy" },
    { 0x003C, "ChannelPage0Mask" },
    { 0x003D, "OperationalDatasetComponents" },
    { 0x003E, "ActiveNetworkFaultsList" },
    { 0x003F, "ExtAddress" },
    { 0x0040, "Rloc16" },
    { 0, NULL }
};
static const value_string matter_cmd_0036_vals[] = {
    { 0x00, "ResetCounts" },
    { 0, NULL }
};
static const value_string matter_attr_0036_vals[] = {
    { 0x0000, "BSSID" },
    { 0x0001, "SecurityType" },
    { 0x0002, "WiFiVersion" },
    { 0x0003, "ChannelNumber" },
    { 0x0004, "RSSI" },
    { 0x0005, "BeaconLostCount" },
    { 0x0006, "BeaconRxCount" },
    { 0x0007, "PacketMulticastRxCount" },
    { 0x0008, "PacketMulticastTxCount" },
    { 0x0009, "PacketUnicastRxCount" },
    { 0x000A, "PacketUnicastTxCount" },
    { 0x000B, "CurrentMaxRate" },
    { 0x000C, "OverrunCount" },
    { 0, NULL }
};
static const value_string matter_cmd_0037_vals[] = {
    { 0x00, "ResetCounts" },
    { 0, NULL }
};
static const value_string matter_attr_0037_vals[] = {
    { 0x0000, "PHYRate" },
    { 0x0001, "FullDuplex" },
    { 0x0002, "PacketRxCount" },
    { 0x0003, "PacketTxCount" },
    { 0x0004, "TxErrCount" },
    { 0x0005, "CollisionCount" },
    { 0x0006, "OverrunCount" },
    { 0x0007, "CarrierDetect" },
    { 0x0008, "TimeSinceReset" },
    { 0, NULL }
};
static const value_string matter_cmd_0038_vals[] = {
    { 0x00, "SetUTCTime" },
    { 0x01, "SetTrustedTimeSource" },
    { 0x02, "SetTimeZone" },
    { 0x04, "SetDSTOffset" },
    { 0x05, "SetDefaultNTP" },
    { 0, NULL }
};
static const value_string matter_rsp_0038_vals[] = {
    { 0x03, "SetTimeZoneResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0038_vals[] = {
    { 0x0000, "UTCTime" },
    { 0x0001, "Granularity" },
    { 0x0002, "TimeSource" },
    { 0x0003, "TrustedTimeSource" },
    { 0x0004, "DefaultNTP" },
    { 0x0005, "TimeZone" },
    { 0x0006, "DSTOffset" },
    { 0x0007, "LocalTime" },
    { 0x0008, "TimeZoneDatabase" },
    { 0x0009, "NTPServerAvailable" },
    { 0x000A, "TimeZoneListMaxSize" },
    { 0x000B, "DSTOffsetListMaxSize" },
    { 0x000C, "SupportsDNSResolve" },
    { 0, NULL }
};
static const value_string matter_cmd_0039_vals[] = {
    { 0x80, "KeepActive" },
    { 0, NULL }
};
static const value_string matter_attr_0039_vals[] = {
    { 0x0000, "DataModelRevision" },
    { 0x0001, "VendorName" },
    { 0x0002, "VendorID" },
    { 0x0003, "ProductName" },
    { 0x0004, "ProductID" },
    { 0x0005, "NodeLabel" },
    { 0x0006, "Location" },
    { 0x0007, "HardwareVersion" },
    { 0x0008, "HardwareVersionString" },
    { 0x0009, "SoftwareVersion" },
    { 0x000A, "SoftwareVersionString" },
    { 0x000B, "ManufacturingDate" },
    { 0x000C, "PartNumber" },
    { 0x000D, "ProductURL" },
    { 0x000E, "ProductLabel" },
    { 0x000F, "SerialNumber" },
    { 0x0010, "LocalConfigDisabled" },
    { 0x0011, "Reachable" },
    { 0x0012, "UniqueID" },
    { 0x0013, "CapabilityMinima" },
    { 0x0014, "ProductAppearance" },
    { 0x0015, "SpecificationVersion" },
    { 0x0016, "MaxPathsPerInvoke" },
    { 0x0018, "ConfigurationVersion" },
    { 0, NULL }
};
static const value_string matter_attr_003b_vals[] = {
    { 0x0000, "NumberOfPositions" },
    { 0x0001, "CurrentPosition" },
    { 0x0002, "MultiPressMax" },
    { 0, NULL }
};
static const value_string matter_cmd_003c_vals[] = {
    { 0x00, "OpenCommissioningWindow" },
    { 0x01, "OpenBasicCommissioningWindow" },
    { 0x02, "RevokeCommissioning" },
    { 0, NULL }
};
static const value_string matter_attr_003c_vals[] = {
    { 0x0000, "WindowStatus" },
    { 0x0001, "AdminFabricIndex" },
    { 0x0002, "AdminVendorId" },
    { 0, NULL }
};
static const value_string matter_cmd_003e_vals[] = {
    { 0x00, "AttestationRequest" },
    { 0x02, "CertificateChainRequest" },
    { 0x04, "CSRRequest" },
    { 0x06, "AddNOC" },
    { 0x07, "UpdateNOC" },
    { 0x09, "UpdateFabricLabel" },
    { 0x0A, "RemoveFabric" },
    { 0x0B, "AddTrustedRootCertificate" },
    { 0x0C, "SetVIDVerificationStatement" },
    { 0x0D, "SignVIDVerificationRequest" },
    { 0, NULL }
};
static const value_string matter_rsp_003e_vals[] = {
    { 0x01, "AttestationResponse" },
    { 0x03, "CertificateChainResponse" },
    { 0x05, "CSRResponse" },
    { 0x08, "NOCResponse" },
    { 0x0E, "SignVIDVerificationResponse" },
    { 0, NULL }
};
static const value_string matter_attr_003e_vals[] = {
    { 0x0000, "NOCs" },
    { 0x0001, "Fabrics" },
    { 0x0002, "SupportedFabrics" },
    { 0x0003, "CommissionedFabrics" },
    { 0x0004, "TrustedRootCertificates" },
    { 0x0005, "CurrentFabricIndex" },
    { 0, NULL }
};
static const value_string matter_cmd_003f_vals[] = {
    { 0x00, "KeySetWrite" },
    { 0x01, "KeySetRead" },
    { 0x03, "KeySetRemove" },
    { 0x04, "KeySetReadAllIndices" },
    { 0, NULL }
};
static const value_string matter_rsp_003f_vals[] = {
    { 0x02, "KeySetReadResponse" },
    { 0x05, "KeySetReadAllIndicesResponse" },
    { 0, NULL }
};
static const value_string matter_attr_003f_vals[] = {
    { 0x0000, "GroupKeyMap" },
    { 0x0001, "GroupTable" },
    { 0x0002, "MaxGroupsPerFabric" },
    { 0x0003, "MaxGroupKeysPerFabric" },
    { 0x0004, "GroupcastAdoption" },
    { 0, NULL }
};
static const value_string matter_attr_0040_vals[] = {
    { 0x0000, "LabelList" },
    { 0, NULL }
};
static const value_string matter_attr_0041_vals[] = {
    { 0x0000, "LabelList" },
    { 0, NULL }
};
static const value_string matter_attr_0045_vals[] = {
    { 0x0000, "StateValue" },
    { 0, NULL }
};
static const value_string matter_cmd_0046_vals[] = {
    { 0x00, "RegisterClient" },
    { 0x02, "UnregisterClient" },
    { 0x03, "StayActiveRequest" },
    { 0, NULL }
};
static const value_string matter_rsp_0046_vals[] = {
    { 0x01, "RegisterClientResponse" },
    { 0x04, "StayActiveResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0046_vals[] = {
    { 0x0000, "IdleModeDuration" },
    { 0x0001, "ActiveModeDuration" },
    { 0x0002, "ActiveModeThreshold" },
    { 0x0003, "RegisteredClients" },
    { 0x0004, "ICDCounter" },
    { 0x0005, "ClientsSupportedPerFabric" },
    { 0x0006, "UserActiveModeTriggerHint" },
    { 0x0007, "UserActiveModeTriggerInstruction" },
    { 0x0008, "OperatingMode" },
    { 0x0009, "MaximumCheckInBackoff" },
    { 0, NULL }
};
static const value_string matter_attr_0049_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_004a_vals[] = {
    { 0x0000, "SupportedDrynessLevels" },
    { 0x0001, "SelectedDrynessLevel" },
    { 0, NULL }
};
static const value_string matter_cmd_0050_vals[] = {
    { 0x00, "ChangeToMode" },
    { 0, NULL }
};
static const value_string matter_attr_0050_vals[] = {
    { 0x0000, "Description" },
    { 0x0001, "StandardNamespace" },
    { 0x0002, "SupportedModes" },
    { 0x0003, "CurrentMode" },
    { 0x0004, "StartUpMode" },
    { 0x0005, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_0051_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_0052_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_0053_vals[] = {
    { 0x0000, "SpinSpeeds" },
    { 0x0001, "SpinSpeedCurrent" },
    { 0x0002, "NumberOfRinses" },
    { 0x0003, "SupportedRinses" },
    { 0, NULL }
};
static const value_string matter_attr_0054_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_0055_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_cmd_0056_vals[] = {
    { 0x00, "SetTemperature" },
    { 0, NULL }
};
static const value_string matter_attr_0056_vals[] = {
    { 0x0000, "TemperatureSetpoint" },
    { 0x0001, "MinTemperature" },
    { 0x0002, "MaxTemperature" },
    { 0x0003, "Step" },
    { 0x0004, "SelectedTemperatureLevel" },
    { 0x0005, "SupportedTemperatureLevels" },
    { 0, NULL }
};
static const value_string matter_attr_0059_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_005b_vals[] = {
    { 0x0000, "AirQuality" },
    { 0, NULL }
};
static const value_string matter_cmd_005c_vals[] = {
    { 0x00, "SelfTestRequest" },
    { 0, NULL }
};
static const value_string matter_attr_005c_vals[] = {
    { 0x0000, "ExpressedState" },
    { 0x0001, "SmokeState" },
    { 0x0002, "COState" },
    { 0x0003, "BatteryAlert" },
    { 0x0004, "DeviceMuted" },
    { 0x0005, "TestInProgress" },
    { 0x0006, "HardwareFaultAlert" },
    { 0x0007, "EndOfServiceAlert" },
    { 0x0008, "InterconnectSmokeAlarm" },
    { 0x0009, "InterconnectCOAlarm" },
    { 0x000A, "ContaminationState" },
    { 0x000B, "SmokeSensitivityLevel" },
    { 0x000C, "ExpiryDate" },
    { 0x000D, "Unmounted" },
    { 0, NULL }
};
static const value_string matter_attr_005e_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_cmd_005f_vals[] = {
    { 0x00, "SetCookingParameters" },
    { 0x01, "AddMoreTime" },
    { 0, NULL }
};
static const value_string matter_attr_005f_vals[] = {
    { 0x0000, "CookTime" },
    { 0x0001, "MaxCookTime" },
    { 0x0002, "PowerSetting" },
    { 0x0003, "MinPower" },
    { 0x0004, "MaxPower" },
    { 0x0005, "PowerStep" },
    { 0x0006, "SupportedWatts" },
    { 0x0007, "SelectedWattIndex" },
    { 0x0008, "WattRating" },
    { 0, NULL }
};
static const value_string matter_cmd_0060_vals[] = {
    { 0x00, "Pause" },
    { 0x01, "Stop" },
    { 0x02, "Start" },
    { 0x03, "Resume" },
    { 0, NULL }
};
static const value_string matter_rsp_0060_vals[] = {
    { 0x04, "OperationalCommandResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0060_vals[] = {
    { 0x0000, "PhaseList" },
    { 0x0001, "CurrentPhase" },
    { 0x0002, "CountdownTime" },
    { 0x0003, "OperationalStateList" },
    { 0x0004, "OperationalState" },
    { 0x0005, "OperationalError" },
    { 0, NULL }
};
static const value_string matter_cmd_0061_vals[] = {
    { 0x80, "GoHome" },
    { 0, NULL }
};
static const value_string matter_cmd_0062_vals[] = {
    { 0x00, "AddScene" },
    { 0x01, "ViewScene" },
    { 0x02, "RemoveScene" },
    { 0x03, "RemoveAllScenes" },
    { 0x04, "StoreScene" },
    { 0x05, "RecallScene" },
    { 0x06, "GetSceneMembership" },
    { 0x40, "CopyScene" },
    { 0, NULL }
};
static const value_string matter_rsp_0062_vals[] = {
    { 0x00, "AddSceneResponse" },
    { 0x01, "ViewSceneResponse" },
    { 0x02, "RemoveSceneResponse" },
    { 0x03, "RemoveAllScenesResponse" },
    { 0x04, "StoreSceneResponse" },
    { 0x06, "GetSceneMembershipResponse" },
    { 0x40, "CopySceneResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0062_vals[] = {
    { 0x0000, "DoNotUse" },
    { 0x0001, "SceneTableSize" },
    { 0x0002, "FabricSceneInfo" },
    { 0, NULL }
};
static const value_string matter_cmd_0064_vals[] = {
    { 0x80, "SetTemperatureAlarmThresholds" },
    { 0, NULL }
};
static const value_string matter_attr_0064_vals[] = {
    { 0x0080, "CriticalOverTemperatureThreshold" },
    { 0x0081, "MajorOverTemperatureThreshold" },
    { 0x0082, "MinorOverTemperatureThreshold" },
    { 0x0083, "MinorUnderTemperatureThreshold" },
    { 0x0084, "MajorUnderTemperatureThreshold" },
    { 0x0085, "CriticalUnderTemperatureThreshold" },
    { 0, NULL }
};
static const value_string matter_cmd_0065_vals[] = {
    { 0x00, "JoinGroup" },
    { 0x01, "LeaveGroup" },
    { 0x03, "UpdateGroupKey" },
    { 0x04, "ConfigureAuxiliaryACL" },
    { 0x05, "GroupcastTesting" },
    { 0, NULL }
};
static const value_string matter_rsp_0065_vals[] = {
    { 0x02, "LeaveGroupResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0065_vals[] = {
    { 0x0000, "Membership" },
    { 0x0001, "MaxMembershipCount" },
    { 0x0002, "MaxMcastAddrCount" },
    { 0x0003, "UsedMcastAddrCount" },
    { 0x0004, "FabricUnderTest" },
    { 0, NULL }
};
static const value_string matter_cmd_0071_vals[] = {
    { 0x00, "ResetCondition" },
    { 0, NULL }
};
static const value_string matter_attr_0071_vals[] = {
    { 0x0000, "Condition" },
    { 0x0001, "DegradationDirection" },
    { 0x0002, "ChangeIndication" },
    { 0x0003, "InPlaceIndicator" },
    { 0x0004, "LastChangedTime" },
    { 0x0005, "ReplacementProductList" },
    { 0, NULL }
};
static const value_string matter_cmd_0072_vals[] = {
    { 0x00, "ResetCondition" },
    { 0, NULL }
};
static const value_string matter_attr_0072_vals[] = {
    { 0x0000, "Condition" },
    { 0x0001, "DegradationDirection" },
    { 0x0002, "ChangeIndication" },
    { 0x0003, "InPlaceIndicator" },
    { 0x0004, "LastChangedTime" },
    { 0x0005, "ReplacementProductList" },
    { 0, NULL }
};
static const value_string matter_cmd_0079_vals[] = {
    { 0x00, "ResetCondition" },
    { 0, NULL }
};
static const value_string matter_attr_0079_vals[] = {
    { 0x0000, "Condition" },
    { 0x0001, "DegradationDirection" },
    { 0x0002, "ChangeIndication" },
    { 0x0003, "InPlaceIndicator" },
    { 0x0004, "LastChangedTime" },
    { 0x0005, "ReplacementProductList" },
    { 0, NULL }
};
static const value_string matter_cmd_0080_vals[] = {
    { 0x00, "SuppressAlarm" },
    { 0x01, "EnableDisableAlarm" },
    { 0, NULL }
};
static const value_string matter_attr_0080_vals[] = {
    { 0x0000, "CurrentSensitivityLevel" },
    { 0x0001, "SupportedSensitivityLevels" },
    { 0x0002, "DefaultSensitivityLevel" },
    { 0x0003, "AlarmsActive" },
    { 0x0004, "AlarmsSuppressed" },
    { 0x0005, "AlarmsEnabled" },
    { 0x0006, "AlarmsSupported" },
    { 0x0007, "SensorFault" },
    { 0, NULL }
};
static const value_string matter_cmd_0081_vals[] = {
    { 0x00, "Open" },
    { 0x01, "Close" },
    { 0, NULL }
};
static const value_string matter_attr_0081_vals[] = {
    { 0x0000, "OpenDuration" },
    { 0x0001, "DefaultOpenDuration" },
    { 0x0002, "AutoCloseTime" },
    { 0x0003, "RemainingDuration" },
    { 0x0004, "CurrentState" },
    { 0x0005, "TargetState" },
    { 0x0006, "CurrentLevel" },
    { 0x0007, "TargetLevel" },
    { 0x0008, "DefaultOpenLevel" },
    { 0x0009, "ValveFault" },
    { 0x000A, "LevelStep" },
    { 0, NULL }
};
static const value_string matter_attr_0090_vals[] = {
    { 0x0000, "PowerMode" },
    { 0x0001, "NumberOfMeasurementTypes" },
    { 0x0002, "Accuracy" },
    { 0x0003, "Ranges" },
    { 0x0004, "Voltage" },
    { 0x0005, "ActiveCurrent" },
    { 0x0006, "ReactiveCurrent" },
    { 0x0007, "ApparentCurrent" },
    { 0x0008, "ActivePower" },
    { 0x0009, "ReactivePower" },
    { 0x000A, "ApparentPower" },
    { 0x000B, "RMSVoltage" },
    { 0x000C, "RMSCurrent" },
    { 0x000D, "RMSPower" },
    { 0x000E, "Frequency" },
    { 0x000F, "HarmonicCurrents" },
    { 0x0010, "HarmonicPhases" },
    { 0x0011, "PowerFactor" },
    { 0x0012, "NeutralCurrent" },
    { 0, NULL }
};
static const value_string matter_attr_0091_vals[] = {
    { 0x0000, "Accuracy" },
    { 0x0001, "CumulativeEnergyImported" },
    { 0x0002, "CumulativeEnergyExported" },
    { 0x0003, "PeriodicEnergyImported" },
    { 0x0004, "PeriodicEnergyExported" },
    { 0x0005, "CumulativeEnergyReset" },
    { 0, NULL }
};
static const value_string matter_cmd_0094_vals[] = {
    { 0x00, "Boost" },
    { 0x01, "CancelBoost" },
    { 0, NULL }
};
static const value_string matter_attr_0094_vals[] = {
    { 0x0000, "HeaterTypes" },
    { 0x0001, "HeatDemand" },
    { 0x0002, "TankVolume" },
    { 0x0003, "EstimatedHeatRequired" },
    { 0x0004, "TankPercentage" },
    { 0x0005, "BoostState" },
    { 0, NULL }
};
static const value_string matter_cmd_0095_vals[] = {
    { 0x00, "GetDetailedPriceRequest" },
    { 0x02, "GetDetailedForecastRequest" },
    { 0, NULL }
};
static const value_string matter_rsp_0095_vals[] = {
    { 0x01, "GetDetailedPriceResponse" },
    { 0x03, "GetDetailedForecastResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0095_vals[] = {
    { 0x0000, "TariffUnit" },
    { 0x0001, "Currency" },
    { 0x0002, "CurrentPrice" },
    { 0x0003, "PriceForecast" },
    { 0, NULL }
};
static const value_string matter_cmd_0097_vals[] = {
    { 0x00, "PresentMessagesRequest" },
    { 0x01, "CancelMessagesRequest" },
    { 0, NULL }
};
static const value_string matter_attr_0097_vals[] = {
    { 0x0000, "Messages" },
    { 0x0001, "ActiveMessageIDs" },
    { 0, NULL }
};
static const value_string matter_cmd_0098_vals[] = {
    { 0x00, "PowerAdjustRequest" },
    { 0x01, "CancelPowerAdjustRequest" },
    { 0x02, "StartTimeAdjustRequest" },
    { 0x03, "PauseRequest" },
    { 0x04, "ResumeRequest" },
    { 0x05, "ModifyForecastRequest" },
    { 0x06, "RequestConstraintBasedForecast" },
    { 0x07, "CancelRequest" },
    { 0, NULL }
};
static const value_string matter_attr_0098_vals[] = {
    { 0x0000, "ESAType" },
    { 0x0001, "ESACanGenerate" },
    { 0x0002, "ESAState" },
    { 0x0003, "AbsMinPower" },
    { 0x0004, "AbsMaxPower" },
    { 0x0005, "PowerAdjustmentCapability" },
    { 0x0006, "Forecast" },
    { 0x0007, "OptOutState" },
    { 0, NULL }
};
static const value_string matter_cmd_0099_vals[] = {
    { 0x01, "Disable" },
    { 0x02, "EnableCharging" },
    { 0x03, "EnableDischarging" },
    { 0x04, "StartDiagnostics" },
    { 0x05, "SetTargets" },
    { 0x06, "GetTargets" },
    { 0x07, "ClearTargets" },
    { 0, NULL }
};
static const value_string matter_rsp_0099_vals[] = {
    { 0x00, "GetTargetsResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0099_vals[] = {
    { 0x0000, "State" },
    { 0x0001, "SupplyState" },
    { 0x0002, "FaultState" },
    { 0x0003, "ChargingEnabledUntil" },
    { 0x0004, "DischargingEnabledUntil" },
    { 0x0005, "CircuitCapacity" },
    { 0x0006, "MinimumChargeCurrent" },
    { 0x0007, "MaximumChargeCurrent" },
    { 0x0008, "MaximumDischargeCurrent" },
    { 0x0009, "UserMaximumChargeCurrent" },
    { 0x000A, "RandomizationDelayWindow" },
    { 0x0023, "NextChargeStartTime" },
    { 0x0024, "NextChargeTargetTime" },
    { 0x0025, "NextChargeRequiredEnergy" },
    { 0x0026, "NextChargeTargetSoC" },
    { 0x0027, "ApproximateEVEfficiency" },
    { 0x0030, "StateOfCharge" },
    { 0x0031, "BatteryCapacity" },
    { 0x0032, "VehicleID" },
    { 0x0040, "SessionID" },
    { 0x0041, "SessionDuration" },
    { 0x0042, "SessionEnergyCharged" },
    { 0x0043, "SessionEnergyDischarged" },
    { 0, NULL }
};
static const value_string matter_attr_009b_vals[] = {
    { 0x0000, "EnergyBalances" },
    { 0x0001, "CurrentEnergyBalance" },
    { 0x0002, "EnergyPriorities" },
    { 0x0003, "LowPowerModeSensitivities" },
    { 0x0004, "CurrentLowPowerModeSensitivity" },
    { 0, NULL }
};
static const value_string matter_attr_009c_vals[] = {
    { 0x0000, "AvailableEndpoints" },
    { 0x0001, "ActiveEndpoints" },
    { 0, NULL }
};
static const value_string matter_attr_009d_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_009e_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_009f_vals[] = {
    { 0x0000, "SupportedModes" },
    { 0x0001, "CurrentMode" },
    { 0x0002, "StartUpMode" },
    { 0x0003, "OnMode" },
    { 0, NULL }
};
static const value_string matter_attr_00a0_vals[] = {
    { 0x0000, "LocalGenerationAvailable" },
    { 0x0001, "CurrentConditions" },
    { 0x0002, "ForecastConditions" },
    { 0, NULL }
};
static const value_string matter_cmd_0101_vals[] = {
    { 0x00, "LockDoor" },
    { 0x01, "UnlockDoor" },
    { 0x02, "Toggle" },
    { 0x03, "UnlockWithTimeout" },
    { 0x0B, "SetWeekDaySchedule" },
    { 0x0C, "GetWeekDaySchedule" },
    { 0x0D, "ClearWeekDaySchedule" },
    { 0x0E, "SetYearDaySchedule" },
    { 0x0F, "GetYearDaySchedule" },
    { 0x10, "ClearYearDaySchedule" },
    { 0x11, "SetHolidaySchedule" },
    { 0x12, "GetHolidaySchedule" },
    { 0x13, "ClearHolidaySchedule" },
    { 0x1A, "SetUser" },
    { 0x1B, "GetUser" },
    { 0x1D, "ClearUser" },
    { 0x22, "SetCredential" },
    { 0x24, "GetCredentialStatus" },
    { 0x26, "ClearCredential" },
    { 0x27, "UnboltDoor" },
    { 0x28, "SetAliroReaderConfig" },
    { 0x29, "ClearAliroReaderConfig" },
    { 0, NULL }
};
static const value_string matter_rsp_0101_vals[] = {
    { 0x0C, "GetWeekDayScheduleResponse" },
    { 0x0F, "GetYearDayScheduleResponse" },
    { 0x12, "GetHolidayScheduleResponse" },
    { 0x1C, "GetUserResponse" },
    { 0x23, "SetCredentialResponse" },
    { 0x25, "GetCredentialStatusResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0101_vals[] = {
    { 0x0000, "LockState" },
    { 0x0001, "LockType" },
    { 0x0002, "ActuatorEnabled" },
    { 0x0003, "DoorState" },
    { 0x0004, "DoorOpenEvents" },
    { 0x0005, "DoorClosedEvents" },
    { 0x0006, "OpenPeriod" },
    { 0x0011, "NumberOfTotalUsersSupported" },
    { 0x0012, "NumberOfPINUsersSupported" },
    { 0x0013, "NumberOfRFIDUsersSupported" },
    { 0x0014, "NumberOfWeekDaySchedulesSupportedPerUser" },
    { 0x0015, "NumberOfYearDaySchedulesSupportedPerUser" },
    { 0x0016, "NumberOfHolidaySchedulesSupported" },
    { 0x0017, "MaxPINCodeLength" },
    { 0x0018, "MinPINCodeLength" },
    { 0x0019, "MaxRFIDCodeLength" },
    { 0x001A, "MinRFIDCodeLength" },
    { 0x001B, "CredentialRulesSupport" },
    { 0x001C, "NumberOfCredentialsSupportedPerUser" },
    { 0x0021, "Language" },
    { 0x0022, "LEDSettings" },
    { 0x0023, "AutoRelockTime" },
    { 0x0024, "SoundVolume" },
    { 0x0025, "OperatingMode" },
    { 0x0026, "SupportedOperatingModes" },
    { 0x0027, "DefaultConfigurationRegister" },
    { 0x0028, "EnableLocalProgramming" },
    { 0x0029, "EnableOneTouchLocking" },
    { 0x002A, "EnableInsideStatusLED" },
    { 0x002B, "EnablePrivacyModeButton" },
    { 0x002C, "LocalProgrammingFeatures" },
    { 0x0030, "WrongCodeEntryLimit" },
    { 0x0031, "UserCodeTemporaryDisableTime" },
    { 0x0032, "SendPINOverTheAir" },
    { 0x0033, "RequirePINforRemoteOperation" },
    { 0x0034, "SecurityLevel" },
    { 0x0035, "ExpiringUserTimeout" },
    { 0x0080, "AliroReaderVerificationKey" },
    { 0x0081, "AliroReaderGroupIdentifier" },
    { 0x0082, "AliroReaderGroupSubIdentifier" },
    { 0x0083, "AliroExpeditedTransactionSupportedProtocolVersions" },
    { 0x0084, "AliroGroupResolvingKey" },
    { 0x0085, "AliroSupportedBLEUWBProtocolVersions" },
    { 0x0086, "AliroBLEAdvertisingVersion" },
    { 0x0087, "NumberOfAliroCredentialIssuerKeysSupported" },
    { 0x0088, "NumberOfAliroEndpointKeysSupported" },
    { 0, NULL }
};
static const value_string matter_cmd_0102_vals[] = {
    { 0x00, "UpOrOpen" },
    { 0x01, "DownOrClose" },
    { 0x02, "StopMotion" },
    { 0x05, "GoToLiftPercentage" },
    { 0x08, "GoToTiltPercentage" },
    { 0, NULL }
};
static const value_string matter_attr_0102_vals[] = {
    { 0x0000, "Type" },
    { 0x0005, "NumberOfActuationsLift" },
    { 0x0006, "NumberOfActuationsTilt" },
    { 0x0007, "ConfigStatus" },
    { 0x0008, "CurrentPositionLiftPercentage" },
    { 0x0009, "CurrentPositionTiltPercentage" },
    { 0x000A, "OperationalStatus" },
    { 0x000B, "TargetPositionLiftPercent100ths" },
    { 0x000C, "TargetPositionTiltPercent100ths" },
    { 0x000D, "EndProductType" },
    { 0x000E, "CurrentPositionLiftPercent100ths" },
    { 0x000F, "CurrentPositionTiltPercent100ths" },
    { 0x0017, "Mode" },
    { 0x001A, "SafetyStatus" },
    { 0, NULL }
};
static const value_string matter_cmd_0104_vals[] = {
    { 0x00, "Stop" },
    { 0x01, "MoveTo" },
    { 0x02, "Calibrate" },
    { 0, NULL }
};
static const value_string matter_attr_0104_vals[] = {
    { 0x0000, "CountdownTime" },
    { 0x0001, "MainState" },
    { 0x0002, "CurrentErrorList" },
    { 0x0003, "OverallCurrentState" },
    { 0x0004, "OverallTargetState" },
    { 0x0005, "LatchControlModes" },
    { 0, NULL }
};
static const value_string matter_cmd_0105_vals[] = {
    { 0x00, "SetTarget" },
    { 0x01, "Step" },
    { 0, NULL }
};
static const value_string matter_attr_0105_vals[] = {
    { 0x0000, "CurrentState" },
    { 0x0001, "TargetState" },
    { 0x0002, "Resolution" },
    { 0x0003, "StepValue" },
    { 0x0004, "Unit" },
    { 0x0005, "UnitRange" },
    { 0x0006, "LimitRange" },
    { 0x0007, "TranslationDirection" },
    { 0x0008, "RotationAxis" },
    { 0x0009, "Overflow" },
    { 0x000A, "ModulationType" },
    { 0x000B, "LatchControlModes" },
    { 0, NULL }
};
static const value_string matter_cmd_0150_vals[] = {
    { 0x00, "SelectAreas" },
    { 0x02, "SkipArea" },
    { 0, NULL }
};
static const value_string matter_rsp_0150_vals[] = {
    { 0x01, "SelectAreasResponse" },
    { 0x03, "SkipAreaResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0150_vals[] = {
    { 0x0000, "SupportedAreas" },
    { 0x0001, "SupportedMaps" },
    { 0x0002, "SelectedAreas" },
    { 0x0003, "CurrentArea" },
    { 0x0004, "EstimatedEndTime" },
    { 0x0005, "Progress" },
    { 0, NULL }
};
static const value_string matter_attr_0200_vals[] = {
    { 0x0000, "MaxPressure" },
    { 0x0001, "MaxSpeed" },
    { 0x0002, "MaxFlow" },
    { 0x0003, "MinConstPressure" },
    { 0x0004, "MaxConstPressure" },
    { 0x0005, "MinCompPressure" },
    { 0x0006, "MaxCompPressure" },
    { 0x0007, "MinConstSpeed" },
    { 0x0008, "MaxConstSpeed" },
    { 0x0009, "MinConstFlow" },
    { 0x000A, "MaxConstFlow" },
    { 0x000B, "MinConstTemp" },
    { 0x000C, "MaxConstTemp" },
    { 0x0010, "PumpStatus" },
    { 0x0011, "EffectiveOperationMode" },
    { 0x0012, "EffectiveControlMode" },
    { 0x0013, "Capacity" },
    { 0x0014, "Speed" },
    { 0x0015, "LifetimeRunningHours" },
    { 0x0016, "Power" },
    { 0x0017, "LifetimeEnergyConsumed" },
    { 0x0020, "OperationMode" },
    { 0x0021, "ControlMode" },
    { 0x0022, "AlarmMask" },
    { 0, NULL }
};
static const value_string matter_cmd_0201_vals[] = {
    { 0x00, "SetpointRaiseLower" },
    { 0x05, "SetActiveScheduleRequest" },
    { 0x06, "SetActivePresetRequest" },
    { 0x07, "AddThermostatSuggestion" },
    { 0x08, "RemoveThermostatSuggestion" },
    { 0, NULL }
};
static const value_string matter_rsp_0201_vals[] = {
    { 0x02, "AddThermostatSuggestionResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0201_vals[] = {
    { 0x0000, "LocalTemperature" },
    { 0x0001, "OutdoorTemperature" },
    { 0x0002, "Occupancy" },
    { 0x0003, "AbsMinHeatSetpointLimit" },
    { 0x0004, "AbsMaxHeatSetpointLimit" },
    { 0x0005, "AbsMinCoolSetpointLimit" },
    { 0x0006, "AbsMaxCoolSetpointLimit" },
    { 0x0007, "PICoolingDemand" },
    { 0x0008, "PIHeatingDemand" },
    { 0x0009, "HVACSystemTypeConfiguration" },
    { 0x0010, "LocalTemperatureCalibration" },
    { 0x0011, "OccupiedCoolingSetpoint" },
    { 0x0012, "OccupiedHeatingSetpoint" },
    { 0x0013, "UnoccupiedCoolingSetpoint" },
    { 0x0014, "UnoccupiedHeatingSetpoint" },
    { 0x0015, "MinHeatSetpointLimit" },
    { 0x0016, "MaxHeatSetpointLimit" },
    { 0x0017, "MinCoolSetpointLimit" },
    { 0x0018, "MaxCoolSetpointLimit" },
    { 0x0019, "MinSetpointDeadBand" },
    { 0x001A, "RemoteSensing" },
    { 0x001B, "ControlSequenceOfOperation" },
    { 0x001C, "SystemMode" },
    { 0x001E, "ThermostatRunningMode" },
    { 0x0023, "TemperatureSetpointHold" },
    { 0x0024, "TemperatureSetpointHoldDuration" },
    { 0x0025, "ThermostatProgrammingOperationMode" },
    { 0x0029, "ThermostatRunningState" },
    { 0x0030, "SetpointChangeSource" },
    { 0x0031, "SetpointChangeAmount" },
    { 0x0032, "SetpointChangeSourceTimestamp" },
    { 0x0034, "OccupiedSetback" },
    { 0x0035, "OccupiedSetbackMin" },
    { 0x0036, "OccupiedSetbackMax" },
    { 0x0037, "UnoccupiedSetback" },
    { 0x0038, "UnoccupiedSetbackMin" },
    { 0x0039, "UnoccupiedSetbackMax" },
    { 0x003A, "EmergencyHeatDelta" },
    { 0x0040, "ACType" },
    { 0x0041, "ACCapacity" },
    { 0x0042, "ACRefrigerantType" },
    { 0x0043, "ACCompressorType" },
    { 0x0044, "ACErrorCode" },
    { 0x0045, "ACLouverPosition" },
    { 0x0046, "ACCoilTemperature" },
    { 0x0047, "ACCapacityFormat" },
    { 0x0048, "PresetTypes" },
    { 0x0049, "ScheduleTypes" },
    { 0x004A, "NumberOfPresets" },
    { 0x004B, "NumberOfSchedules" },
    { 0x004C, "NumberOfScheduleTransitions" },
    { 0x004D, "NumberOfScheduleTransitionPerDay" },
    { 0x004E, "ActivePresetHandle" },
    { 0x004F, "ActiveScheduleHandle" },
    { 0x0050, "Presets" },
    { 0x0051, "Schedules" },
    { 0x0052, "SetpointHoldExpiryTimestamp" },
    { 0x0053, "MaxThermostatSuggestions" },
    { 0x0054, "ThermostatSuggestions" },
    { 0x0055, "CurrentThermostatSuggestion" },
    { 0x0056, "ThermostatSuggestionNotFollowingReason" },
    { 0, NULL }
};
static const value_string matter_cmd_0202_vals[] = {
    { 0x00, "Step" },
    { 0, NULL }
};
static const value_string matter_attr_0202_vals[] = {
    { 0x0000, "FanMode" },
    { 0x0001, "FanModeSequence" },
    { 0x0002, "PercentSetting" },
    { 0x0003, "PercentCurrent" },
    { 0x0004, "SpeedMax" },
    { 0x0005, "SpeedSetting" },
    { 0x0006, "SpeedCurrent" },
    { 0x0007, "RockSupport" },
    { 0x0008, "RockSetting" },
    { 0x0009, "WindSupport" },
    { 0x000A, "WindSetting" },
    { 0x000B, "AirflowDirection" },
    { 0, NULL }
};
static const value_string matter_attr_0204_vals[] = {
    { 0x0000, "TemperatureDisplayMode" },
    { 0x0001, "KeypadLockout" },
    { 0x0002, "ScheduleProgrammingVisibility" },
    { 0, NULL }
};
static const value_string matter_cmd_0300_vals[] = {
    { 0x00, "MoveToHue" },
    { 0x01, "MoveHue" },
    { 0x02, "StepHue" },
    { 0x03, "MoveToSaturation" },
    { 0x04, "MoveSaturation" },
    { 0x05, "StepSaturation" },
    { 0x06, "MoveToHueAndSaturation" },
    { 0x07, "MoveToColor" },
    { 0x08, "MoveColor" },
    { 0x09, "StepColor" },
    { 0x0A, "MoveToColorTemperature" },
    { 0x40, "EnhancedMoveToHue" },
    { 0x41, "EnhancedMoveHue" },
    { 0x42, "EnhancedStepHue" },
    { 0x43, "EnhancedMoveToHueAndSaturation" },
    { 0x44, "ColorLoopSet" },
    { 0x47, "StopMoveStep" },
    { 0x4B, "MoveColorTemperature" },
    { 0x4C, "StepColorTemperature" },
    { 0, NULL }
};
static const value_string matter_attr_0300_vals[] = {
    { 0x0000, "CurrentHue" },
    { 0x0001, "CurrentSaturation" },
    { 0x0002, "RemainingTime" },
    { 0x0003, "CurrentX" },
    { 0x0004, "CurrentY" },
    { 0x0005, "DriftCompensation" },
    { 0x0006, "CompensationText" },
    { 0x0007, "ColorTemperatureMireds" },
    { 0x0008, "ColorMode" },
    { 0x000F, "Options" },
    { 0x0010, "NumberOfPrimaries" },
    { 0x0011, "Primary1X" },
    { 0x0012, "Primary1Y" },
    { 0x0013, "Primary1Intensity" },
    { 0x0015, "Primary2X" },
    { 0x0016, "Primary2Y" },
    { 0x0017, "Primary2Intensity" },
    { 0x0019, "Primary3X" },
    { 0x001A, "Primary3Y" },
    { 0x001B, "Primary3Intensity" },
    { 0x0020, "Primary4X" },
    { 0x0021, "Primary4Y" },
    { 0x0022, "Primary4Intensity" },
    { 0x0024, "Primary5X" },
    { 0x0025, "Primary5Y" },
    { 0x0026, "Primary5Intensity" },
    { 0x0028, "Primary6X" },
    { 0x0029, "Primary6Y" },
    { 0x002A, "Primary6Intensity" },
    { 0x0030, "WhitePointX" },
    { 0x0031, "WhitePointY" },
    { 0x0032, "ColorPointRX" },
    { 0x0033, "ColorPointRY" },
    { 0x0034, "ColorPointRIntensity" },
    { 0x0036, "ColorPointGX" },
    { 0x0037, "ColorPointGY" },
    { 0x0038, "ColorPointGIntensity" },
    { 0x003A, "ColorPointBX" },
    { 0x003B, "ColorPointBY" },
    { 0x003C, "ColorPointBIntensity" },
    { 0x4000, "EnhancedCurrentHue" },
    { 0x4001, "EnhancedColorMode" },
    { 0x4002, "ColorLoopActive" },
    { 0x4003, "ColorLoopDirection" },
    { 0x4004, "ColorLoopTime" },
    { 0x4005, "ColorLoopStartEnhancedHue" },
    { 0x4006, "ColorLoopStoredEnhancedHue" },
    { 0x400A, "ColorCapabilities" },
    { 0x400B, "ColorTempPhysicalMinMireds" },
    { 0x400C, "ColorTempPhysicalMaxMireds" },
    { 0x400D, "CoupleColorTempToLevelMinMireds" },
    { 0x4010, "StartUpColorTemperatureMireds" },
    { 0, NULL }
};
static const value_string matter_attr_0400_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "Tolerance" },
    { 0x0004, "LightSensorType" },
    { 0, NULL }
};
static const value_string matter_attr_0402_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "Tolerance" },
    { 0, NULL }
};
static const value_string matter_attr_0403_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "Tolerance" },
    { 0x0010, "ScaledValue" },
    { 0x0011, "MinScaledValue" },
    { 0x0012, "MaxScaledValue" },
    { 0x0013, "ScaledTolerance" },
    { 0x0014, "Scale" },
    { 0, NULL }
};
static const value_string matter_attr_0404_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "Tolerance" },
    { 0, NULL }
};
static const value_string matter_attr_0405_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "Tolerance" },
    { 0, NULL }
};
static const value_string matter_attr_0406_vals[] = {
    { 0x0000, "Occupancy" },
    { 0x0001, "OccupancySensorType" },
    { 0x0002, "OccupancySensorTypeBitmap" },
    { 0x0003, "HoldTime" },
    { 0x0004, "HoldTimeLimits" },
    { 0x0010, "PIROccupiedToUnoccupiedDelay" },
    { 0x0011, "PIRUnoccupiedToOccupiedDelay" },
    { 0x0012, "PIRUnoccupiedToOccupiedThreshold" },
    { 0x0020, "UltrasonicOccupiedToUnoccupiedDelay" },
    { 0x0021, "UltrasonicUnoccupiedToOccupiedDelay" },
    { 0x0022, "UltrasonicUnoccupiedToOccupiedThreshold" },
    { 0x0030, "PhysicalContactOccupiedToUnoccupiedDelay" },
    { 0x0031, "PhysicalContactUnoccupiedToOccupiedDelay" },
    { 0x0032, "PhysicalContactUnoccupiedToOccupiedThreshold" },
    { 0, NULL }
};
static const value_string matter_attr_040c_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_040d_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_0413_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_0415_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_042a_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_042b_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_042c_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_042d_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_042e_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_042f_vals[] = {
    { 0x0000, "MeasuredValue" },
    { 0x0001, "MinMeasuredValue" },
    { 0x0002, "MaxMeasuredValue" },
    { 0x0003, "PeakMeasuredValue" },
    { 0x0004, "PeakMeasuredValueWindow" },
    { 0x0005, "AverageMeasuredValue" },
    { 0x0006, "AverageMeasuredValueWindow" },
    { 0x0007, "Uncertainty" },
    { 0x0008, "MeasurementUnit" },
    { 0x0009, "MeasurementMedium" },
    { 0x000A, "LevelValue" },
    { 0, NULL }
};
static const value_string matter_attr_0430_vals[] = {
    { 0x0000, "SoilMoistureMeasurementLimits" },
    { 0x0001, "SoilMoistureMeasuredValue" },
    { 0, NULL }
};
static const value_string matter_attr_0431_vals[] = {
    { 0x0000, "HumanActivityDetected" },
    { 0x0001, "ObjectIdentified" },
    { 0x0002, "AudioContextDetected" },
    { 0x0003, "AmbientContextType" },
    { 0x0004, "AmbientContextTypeSupported" },
    { 0x0005, "ObjectCountThresholdReached" },
    { 0x0006, "ObjectCountConfig" },
    { 0x0007, "ObjectCount" },
    { 0x0008, "SimultaneousDetectionLimit" },
    { 0x0009, "HoldTime" },
    { 0x000A, "HoldTimeLimits" },
    { 0x000B, "PredictedActivity" },
    { 0, NULL }
};
static const value_string matter_cmd_0451_vals[] = {
    { 0x00, "NetworkPassphraseRequest" },
    { 0, NULL }
};
static const value_string matter_rsp_0451_vals[] = {
    { 0x01, "NetworkPassphraseResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0451_vals[] = {
    { 0x0000, "SSID" },
    { 0x0001, "PassphraseSurrogate" },
    { 0, NULL }
};
static const value_string matter_cmd_0452_vals[] = {
    { 0x00, "GetActiveDatasetRequest" },
    { 0x01, "GetPendingDatasetRequest" },
    { 0x03, "SetActiveDatasetRequest" },
    { 0x04, "SetPendingDatasetRequest" },
    { 0, NULL }
};
static const value_string matter_rsp_0452_vals[] = {
    { 0x02, "DatasetResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0452_vals[] = {
    { 0x0000, "BorderRouterName" },
    { 0x0001, "BorderAgentID" },
    { 0x0002, "ThreadVersion" },
    { 0x0003, "InterfaceEnabled" },
    { 0x0004, "ActiveDatasetTimestamp" },
    { 0x0005, "PendingDatasetTimestamp" },
    { 0, NULL }
};
static const value_string matter_cmd_0453_vals[] = {
    { 0x00, "AddNetwork" },
    { 0x01, "RemoveNetwork" },
    { 0x02, "GetOperationalDataset" },
    { 0, NULL }
};
static const value_string matter_rsp_0453_vals[] = {
    { 0x03, "OperationalDatasetResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0453_vals[] = {
    { 0x0000, "PreferredExtendedPanID" },
    { 0x0001, "ThreadNetworks" },
    { 0x0002, "ThreadNetworkTableSize" },
    { 0, NULL }
};
static const value_string matter_attr_0503_vals[] = {
    { 0x0000, "MACAddress" },
    { 0x0001, "LinkLocalAddress" },
    { 0, NULL }
};
static const value_string matter_cmd_0504_vals[] = {
    { 0x00, "ChangeChannel" },
    { 0x02, "ChangeChannelByNumber" },
    { 0x03, "SkipChannel" },
    { 0x04, "GetProgramGuide" },
    { 0x06, "RecordProgram" },
    { 0x07, "CancelRecordProgram" },
    { 0, NULL }
};
static const value_string matter_rsp_0504_vals[] = {
    { 0x01, "ChangeChannelResponse" },
    { 0x05, "ProgramGuideResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0504_vals[] = {
    { 0x0000, "ChannelList" },
    { 0x0001, "Lineup" },
    { 0x0002, "CurrentChannel" },
    { 0, NULL }
};
static const value_string matter_cmd_0505_vals[] = {
    { 0x00, "NavigateTarget" },
    { 0, NULL }
};
static const value_string matter_rsp_0505_vals[] = {
    { 0x01, "NavigateTargetResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0505_vals[] = {
    { 0x0000, "TargetList" },
    { 0x0001, "CurrentTarget" },
    { 0, NULL }
};
static const value_string matter_cmd_0506_vals[] = {
    { 0x00, "Play" },
    { 0x01, "Pause" },
    { 0x02, "Stop" },
    { 0x03, "StartOver" },
    { 0x04, "Previous" },
    { 0x05, "Next" },
    { 0x06, "Rewind" },
    { 0x07, "FastForward" },
    { 0x08, "SkipForward" },
    { 0x09, "SkipBackward" },
    { 0x0B, "Seek" },
    { 0x0C, "ActivateAudioTrack" },
    { 0x0D, "ActivateTextTrack" },
    { 0x0E, "DeactivateTextTrack" },
    { 0, NULL }
};
static const value_string matter_rsp_0506_vals[] = {
    { 0x0A, "PlaybackResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0506_vals[] = {
    { 0x0000, "CurrentState" },
    { 0x0001, "StartTime" },
    { 0x0002, "Duration" },
    { 0x0003, "SampledPosition" },
    { 0x0004, "PlaybackSpeed" },
    { 0x0005, "SeekRangeEnd" },
    { 0x0006, "SeekRangeStart" },
    { 0x0007, "ActiveAudioTrack" },
    { 0x0008, "AvailableAudioTracks" },
    { 0x0009, "ActiveTextTrack" },
    { 0x000A, "AvailableTextTracks" },
    { 0, NULL }
};
static const value_string matter_cmd_0507_vals[] = {
    { 0x00, "SelectInput" },
    { 0x01, "ShowInputStatus" },
    { 0x02, "HideInputStatus" },
    { 0x03, "RenameInput" },
    { 0, NULL }
};
static const value_string matter_attr_0507_vals[] = {
    { 0x0000, "InputList" },
    { 0x0001, "CurrentInput" },
    { 0, NULL }
};
static const value_string matter_cmd_0508_vals[] = {
    { 0x00, "Sleep" },
    { 0, NULL }
};
static const value_string matter_cmd_0509_vals[] = {
    { 0x00, "SendKey" },
    { 0, NULL }
};
static const value_string matter_rsp_0509_vals[] = {
    { 0x01, "SendKeyResponse" },
    { 0, NULL }
};
static const value_string matter_cmd_050a_vals[] = {
    { 0x00, "LaunchContent" },
    { 0x01, "LaunchURL" },
    { 0, NULL }
};
static const value_string matter_rsp_050a_vals[] = {
    { 0x02, "LauncherResponse" },
    { 0, NULL }
};
static const value_string matter_attr_050a_vals[] = {
    { 0x0000, "AcceptHeader" },
    { 0x0001, "SupportedStreamingProtocols" },
    { 0, NULL }
};
static const value_string matter_cmd_050b_vals[] = {
    { 0x00, "SelectOutput" },
    { 0x01, "RenameOutput" },
    { 0, NULL }
};
static const value_string matter_attr_050b_vals[] = {
    { 0x0000, "OutputList" },
    { 0x0001, "CurrentOutput" },
    { 0, NULL }
};
static const value_string matter_cmd_050c_vals[] = {
    { 0x00, "LaunchApp" },
    { 0x01, "StopApp" },
    { 0x02, "HideApp" },
    { 0, NULL }
};
static const value_string matter_rsp_050c_vals[] = {
    { 0x03, "LauncherResponse" },
    { 0, NULL }
};
static const value_string matter_attr_050c_vals[] = {
    { 0x0000, "CatalogList" },
    { 0x0001, "CurrentApp" },
    { 0, NULL }
};
static const value_string matter_attr_050d_vals[] = {
    { 0x0000, "VendorName" },
    { 0x0001, "VendorID" },
    { 0x0002, "ApplicationName" },
    { 0x0003, "ProductID" },
    { 0x0004, "Application" },
    { 0x0005, "Status" },
    { 0x0006, "ApplicationVersion" },
    { 0x0007, "AllowedVendorList" },
    { 0, NULL }
};
static const value_string matter_cmd_050e_vals[] = {
    { 0x00, "GetSetupPIN" },
    { 0x02, "Login" },
    { 0x03, "Logout" },
    { 0, NULL }
};
static const value_string matter_rsp_050e_vals[] = {
    { 0x01, "GetSetupPINResponse" },
    { 0, NULL }
};
static const value_string matter_cmd_050f_vals[] = {
    { 0x00, "UpdatePIN" },
    { 0x01, "ResetPIN" },
    { 0x03, "Enable" },
    { 0x04, "Disable" },
    { 0x05, "AddBonusTime" },
    { 0x06, "SetScreenDailyTime" },
    { 0x07, "BlockUnratedContent" },
    { 0x08, "UnblockUnratedContent" },
    { 0x09, "SetOnDemandRatingThreshold" },
    { 0x0A, "SetScheduledContentRatingThreshold" },
    { 0x0B, "AddBlockChannels" },
    { 0x0C, "RemoveBlockChannels" },
    { 0x0D, "AddBlockApplications" },
    { 0x0E, "RemoveBlockApplications" },
    { 0x0F, "SetBlockContentTimeWindow" },
    { 0x10, "RemoveBlockContentTimeWindow" },
    { 0, NULL }
};
static const value_string matter_rsp_050f_vals[] = {
    { 0x02, "ResetPINResponse" },
    { 0, NULL }
};
static const value_string matter_attr_050f_vals[] = {
    { 0x0000, "Enabled" },
    { 0x0001, "OnDemandRatings" },
    { 0x0002, "OnDemandRatingThreshold" },
    { 0x0003, "ScheduledContentRatings" },
    { 0x0004, "ScheduledContentRatingThreshold" },
    { 0x0005, "ScreenDailyTime" },
    { 0x0006, "RemainingScreenTime" },
    { 0x0007, "BlockUnrated" },
    { 0x0008, "BlockChannelList" },
    { 0x0009, "BlockApplicationList" },
    { 0x000A, "BlockContentTimeWindow" },
    { 0, NULL }
};
static const value_string matter_cmd_0510_vals[] = {
    { 0x00, "ContentAppMessage" },
    { 0, NULL }
};
static const value_string matter_rsp_0510_vals[] = {
    { 0x01, "ContentAppMessageResponse" },
    { 0, NULL }
};
static const value_string matter_cmd_0550_vals[] = {
    { 0x00, "CreateTwoDCartesianZone" },
    { 0x02, "UpdateTwoDCartesianZone" },
    { 0x03, "RemoveZone" },
    { 0x04, "CreateOrUpdateTrigger" },
    { 0x05, "RemoveTrigger" },
    { 0, NULL }
};
static const value_string matter_rsp_0550_vals[] = {
    { 0x01, "CreateTwoDCartesianZoneResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0550_vals[] = {
    { 0x0000, "MaxUserDefinedZones" },
    { 0x0001, "MaxZones" },
    { 0x0002, "Zones" },
    { 0x0003, "Triggers" },
    { 0x0004, "SensitivityMax" },
    { 0x0005, "Sensitivity" },
    { 0x0006, "TwoDCartesianMax" },
    { 0, NULL }
};
static const value_string matter_cmd_0551_vals[] = {
    { 0x00, "AudioStreamAllocate" },
    { 0x02, "AudioStreamDeallocate" },
    { 0x03, "VideoStreamAllocate" },
    { 0x05, "VideoStreamModify" },
    { 0x06, "VideoStreamDeallocate" },
    { 0x07, "SnapshotStreamAllocate" },
    { 0x09, "SnapshotStreamModify" },
    { 0x0A, "SnapshotStreamDeallocate" },
    { 0x0B, "SetStreamPriorities" },
    { 0x0C, "CaptureSnapshot" },
    { 0, NULL }
};
static const value_string matter_rsp_0551_vals[] = {
    { 0x01, "AudioStreamAllocateResponse" },
    { 0x04, "VideoStreamAllocateResponse" },
    { 0x08, "SnapshotStreamAllocateResponse" },
    { 0x0D, "CaptureSnapshotResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0551_vals[] = {
    { 0x0000, "MaxConcurrentEncoders" },
    { 0x0001, "MaxEncodedPixelRate" },
    { 0x0002, "VideoSensorParams" },
    { 0x0003, "NightVisionUsesInfrared" },
    { 0x0004, "MinViewportResolution" },
    { 0x0005, "RateDistortionTradeOffPoints" },
    { 0x0006, "MaxContentBufferSize" },
    { 0x0007, "MicrophoneCapabilities" },
    { 0x0008, "SpeakerCapabilities" },
    { 0x0009, "TwoWayTalkSupport" },
    { 0x000A, "SnapshotCapabilities" },
    { 0x000B, "MaxNetworkBandwidth" },
    { 0x000C, "CurrentFrameRate" },
    { 0x000D, "HDRModeEnabled" },
    { 0x000E, "SupportedStreamUsages" },
    { 0x000F, "AllocatedVideoStreams" },
    { 0x0010, "AllocatedAudioStreams" },
    { 0x0011, "AllocatedSnapshotStreams" },
    { 0x0012, "StreamUsagePriorities" },
    { 0x0013, "SoftRecordingPrivacyModeEnabled" },
    { 0x0014, "SoftLivestreamPrivacyModeEnabled" },
    { 0x0015, "HardPrivacyModeOn" },
    { 0x0016, "NightVision" },
    { 0x0017, "NightVisionIllum" },
    { 0x0018, "Viewport" },
    { 0x0019, "SpeakerMuted" },
    { 0x001A, "SpeakerVolumeLevel" },
    { 0x001B, "SpeakerMaxLevel" },
    { 0x001C, "SpeakerMinLevel" },
    { 0x001D, "MicrophoneMuted" },
    { 0x001E, "MicrophoneVolumeLevel" },
    { 0x001F, "MicrophoneMaxLevel" },
    { 0x0020, "MicrophoneMinLevel" },
    { 0x0021, "MicrophoneAGCEnabled" },
    { 0x0022, "ImageRotation" },
    { 0x0023, "ImageFlipHorizontal" },
    { 0x0024, "ImageFlipVertical" },
    { 0x0025, "LocalVideoRecordingEnabled" },
    { 0x0026, "LocalSnapshotRecordingEnabled" },
    { 0x0027, "StatusLightEnabled" },
    { 0x0028, "StatusLightBrightness" },
    { 0x0029, "ImageRotationDiscreteAngles" },
    { 0, NULL }
};
static const value_string matter_cmd_0552_vals[] = {
    { 0x00, "MPTZSetPosition" },
    { 0x01, "MPTZRelativeMove" },
    { 0x02, "MPTZMoveToPreset" },
    { 0x03, "MPTZSavePreset" },
    { 0x04, "MPTZRemovePreset" },
    { 0x05, "DPTZSetViewport" },
    { 0x06, "DPTZRelativeMove" },
    { 0, NULL }
};
static const value_string matter_attr_0552_vals[] = {
    { 0x0000, "MPTZPosition" },
    { 0x0001, "MaxPresets" },
    { 0x0002, "MPTZPresets" },
    { 0x0003, "DPTZStreams" },
    { 0x0004, "ZoomMax" },
    { 0x0005, "TiltMin" },
    { 0x0006, "TiltMax" },
    { 0x0007, "PanMin" },
    { 0x0008, "PanMax" },
    { 0x0009, "MovementState" },
    { 0, NULL }
};
static const value_string matter_cmd_0553_vals[] = {
    { 0x00, "SolicitOffer" },
    { 0x02, "ProvideOffer" },
    { 0x04, "ProvideAnswer" },
    { 0x05, "ProvideICECandidates" },
    { 0x06, "EndSession" },
    { 0, NULL }
};
static const value_string matter_rsp_0553_vals[] = {
    { 0x01, "SolicitOfferResponse" },
    { 0x03, "ProvideOfferResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0553_vals[] = {
    { 0x0000, "CurrentSessions" },
    { 0, NULL }
};
static const value_string matter_cmd_0554_vals[] = {
    { 0x00, "Offer" },
    { 0x01, "Answer" },
    { 0x02, "ICECandidates" },
    { 0x03, "End" },
    { 0, NULL }
};
static const value_string matter_attr_0554_vals[] = {
    { 0x0000, "CurrentSessions" },
    { 0, NULL }
};
static const value_string matter_cmd_0555_vals[] = {
    { 0x00, "AllocatePushTransport" },
    { 0x02, "DeallocatePushTransport" },
    { 0x03, "ModifyPushTransport" },
    { 0x04, "SetTransportStatus" },
    { 0x05, "ManuallyTriggerTransport" },
    { 0x06, "FindTransport" },
    { 0, NULL }
};
static const value_string matter_rsp_0555_vals[] = {
    { 0x01, "AllocatePushTransportResponse" },
    { 0x07, "FindTransportResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0555_vals[] = {
    { 0x0000, "SupportedFormats" },
    { 0x0001, "CurrentConnections" },
    { 0, NULL }
};
static const value_string matter_cmd_0556_vals[] = {
    { 0x00, "PlayChimeSound" },
    { 0, NULL }
};
static const value_string matter_attr_0556_vals[] = {
    { 0x0000, "InstalledChimeSounds" },
    { 0x0001, "SelectedChime" },
    { 0x0002, "Enabled" },
    { 0, NULL }
};
static const value_string matter_cmd_0700_vals[] = {
    { 0x00, "GetTariffComponent" },
    { 0x01, "GetDayEntry" },
    { 0, NULL }
};
static const value_string matter_rsp_0700_vals[] = {
    { 0x00, "GetTariffComponentResponse" },
    { 0x01, "GetDayEntryResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0700_vals[] = {
    { 0x0000, "TariffInfo" },
    { 0x0001, "TariffUnit" },
    { 0x0002, "StartDate" },
    { 0x0003, "DayEntries" },
    { 0x0004, "DayPatterns" },
    { 0x0005, "CalendarPeriods" },
    { 0x0006, "IndividualDays" },
    { 0x0007, "CurrentDay" },
    { 0x0008, "NextDay" },
    { 0x0009, "CurrentDayEntry" },
    { 0x000A, "CurrentDayEntryDate" },
    { 0x000B, "NextDayEntry" },
    { 0x000C, "NextDayEntryDate" },
    { 0x000D, "TariffComponents" },
    { 0x000E, "TariffPeriods" },
    { 0x000F, "CurrentTariffComponents" },
    { 0x0010, "NextTariffComponents" },
    { 0x0011, "DefaultRandomizationOffset" },
    { 0x0012, "DefaultRandomizationType" },
    { 0, NULL }
};
static const value_string matter_attr_0750_vals[] = {
    { 0x0000, "DeviceDirectory" },
    { 0x0001, "LocationDirectory" },
    { 0, NULL }
};
static const value_string matter_cmd_0751_vals[] = {
    { 0x00, "RequestCommissioningApproval" },
    { 0x01, "CommissionNode" },
    { 0, NULL }
};
static const value_string matter_rsp_0751_vals[] = {
    { 0x02, "ReverseOpenCommissioningWindow" },
    { 0, NULL }
};
static const value_string matter_attr_0751_vals[] = {
    { 0x0000, "SupportedDeviceCategories" },
    { 0, NULL }
};
static const value_string matter_cmd_0752_vals[] = {
    { 0x00, "AddKeySet" },
    { 0x01, "UpdateKeySet" },
    { 0x02, "RemoveKeySet" },
    { 0x03, "AddGroup" },
    { 0x04, "UpdateGroup" },
    { 0x05, "RemoveGroup" },
    { 0x06, "AddAdmin" },
    { 0x07, "UpdateAdmin" },
    { 0x08, "RemoveAdmin" },
    { 0x09, "AddPendingNode" },
    { 0x0A, "RefreshNode" },
    { 0x0B, "UpdateNode" },
    { 0x0C, "RemoveNode" },
    { 0x0D, "UpdateEndpointForNode" },
    { 0x0E, "AddGroupIDToEndpointForNode" },
    { 0x0F, "RemoveGroupIDFromEndpointForNode" },
    { 0x10, "AddBindingToEndpointForNode" },
    { 0x11, "RemoveBindingFromEndpointForNode" },
    { 0x12, "AddACLToNode" },
    { 0x13, "RemoveACLFromNode" },
    { 0, NULL }
};
static const value_string matter_attr_0752_vals[] = {
    { 0x0000, "AnchorRootCA" },
    { 0x0001, "AnchorNodeID" },
    { 0x0002, "AnchorVendorID" },
    { 0x0003, "FriendlyName" },
    { 0x0004, "GroupKeySetList" },
    { 0x0005, "GroupList" },
    { 0x0006, "NodeList" },
    { 0x0007, "AdminList" },
    { 0x0008, "Status" },
    { 0x0009, "EndpointGroupIDList" },
    { 0x000A, "EndpointBindingList" },
    { 0x000B, "NodeKeySetList" },
    { 0x000C, "NodeACLList" },
    { 0x000D, "NodeEndpointList" },
    { 0, NULL }
};
static const value_string matter_cmd_0753_vals[] = {
    { 0x00, "ICACCSRRequest" },
    { 0x02, "AddICAC" },
    { 0x04, "OpenJointCommissioningWindow" },
    { 0x05, "TransferAnchorRequest" },
    { 0x07, "TransferAnchorComplete" },
    { 0x08, "AnnounceJointFabricAdministrator" },
    { 0, NULL }
};
static const value_string matter_rsp_0753_vals[] = {
    { 0x01, "ICACCSRResponse" },
    { 0x03, "ICACResponse" },
    { 0x06, "TransferAnchorResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0753_vals[] = {
    { 0x0000, "AdministratorFabricIndex" },
    { 0, NULL }
};
static const value_string matter_cmd_0801_vals[] = {
    { 0x00, "ProvisionRootCertificate" },
    { 0x02, "FindRootCertificate" },
    { 0x04, "LookupRootCertificate" },
    { 0x06, "RemoveRootCertificate" },
    { 0x07, "ClientCSR" },
    { 0x09, "ProvisionClientCertificate" },
    { 0x0A, "FindClientCertificate" },
    { 0x0C, "LookupClientCertificate" },
    { 0x0E, "RemoveClientCertificate" },
    { 0, NULL }
};
static const value_string matter_rsp_0801_vals[] = {
    { 0x01, "ProvisionRootCertificateResponse" },
    { 0x03, "FindRootCertificateResponse" },
    { 0x05, "LookupRootCertificateResponse" },
    { 0x08, "ClientCSRResponse" },
    { 0x0B, "FindClientCertificateResponse" },
    { 0x0D, "LookupClientCertificateResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0801_vals[] = {
    { 0x0000, "MaxRootCertificates" },
    { 0x0001, "ProvisionedRootCertificates" },
    { 0x0002, "MaxClientCertificates" },
    { 0x0003, "ProvisionedClientCertificates" },
    { 0, NULL }
};
static const value_string matter_cmd_0802_vals[] = {
    { 0x00, "ProvisionEndpoint" },
    { 0x02, "FindEndpoint" },
    { 0x04, "RemoveEndpoint" },
    { 0, NULL }
};
static const value_string matter_rsp_0802_vals[] = {
    { 0x01, "ProvisionEndpointResponse" },
    { 0x03, "FindEndpointResponse" },
    { 0, NULL }
};
static const value_string matter_attr_0802_vals[] = {
    { 0x0000, "MaxProvisioned" },
    { 0x0001, "ProvisionedEndpoints" },
    { 0, NULL }
};
static const value_string matter_attr_0b06_vals[] = {
    { 0x0000, "MeterType" },
    { 0x0001, "PointOfDelivery" },
    { 0x0002, "MeterSerialNumber" },
    { 0x0003, "ProtocolVersion" },
    { 0x0004, "PowerThreshold" },
    { 0, NULL }
};
static const value_string matter_attr_0b07_vals[] = {
    { 0x0000, "MeteredQuantity" },
    { 0x0001, "MeteredQuantityTimestamp" },
    { 0x0002, "TariffUnit" },
    { 0x0003, "MaximumMeteredQuantities" },
    { 0, NULL }
};

typedef struct { uint32_t cluster_id; const value_string *cmds; const value_string *rsps; const value_string *attrs; } matter_cluster_members_t;

static const matter_cluster_members_t matter_cluster_members[] = {
    { 0x0003, matter_cmd_0003_vals, NULL, matter_attr_0003_vals },
    { 0x0004, matter_cmd_0004_vals, matter_rsp_0004_vals, matter_attr_0004_vals },
    { 0x0006, matter_cmd_0006_vals, NULL, matter_attr_0006_vals },
    { 0x0008, matter_cmd_0008_vals, NULL, matter_attr_0008_vals },
    { 0x001D, NULL, NULL, matter_attr_001d_vals },
    { 0x001E, NULL, NULL, matter_attr_001e_vals },
    { 0x001F, matter_cmd_001f_vals, matter_rsp_001f_vals, matter_attr_001f_vals },
    { 0x0025, matter_cmd_0025_vals, NULL, matter_attr_0025_vals },
    { 0x0028, NULL, NULL, matter_attr_0028_vals },
    { 0x0029, matter_cmd_0029_vals, matter_rsp_0029_vals, NULL },
    { 0x002A, matter_cmd_002a_vals, NULL, matter_attr_002a_vals },
    { 0x002B, NULL, NULL, matter_attr_002b_vals },
    { 0x002C, NULL, NULL, matter_attr_002c_vals },
    { 0x002D, NULL, NULL, matter_attr_002d_vals },
    { 0x002E, NULL, NULL, matter_attr_002e_vals },
    { 0x002F, NULL, NULL, matter_attr_002f_vals },
    { 0x0030, matter_cmd_0030_vals, matter_rsp_0030_vals, matter_attr_0030_vals },
    { 0x0031, matter_cmd_0031_vals, matter_rsp_0031_vals, matter_attr_0031_vals },
    { 0x0032, matter_cmd_0032_vals, matter_rsp_0032_vals, NULL },
    { 0x0033, matter_cmd_0033_vals, matter_rsp_0033_vals, matter_attr_0033_vals },
    { 0x0034, matter_cmd_0034_vals, NULL, matter_attr_0034_vals },
    { 0x0035, matter_cmd_0035_vals, NULL, matter_attr_0035_vals },
    { 0x0036, matter_cmd_0036_vals, NULL, matter_attr_0036_vals },
    { 0x0037, matter_cmd_0037_vals, NULL, matter_attr_0037_vals },
    { 0x0038, matter_cmd_0038_vals, matter_rsp_0038_vals, matter_attr_0038_vals },
    { 0x0039, matter_cmd_0039_vals, NULL, matter_attr_0039_vals },
    { 0x003B, NULL, NULL, matter_attr_003b_vals },
    { 0x003C, matter_cmd_003c_vals, NULL, matter_attr_003c_vals },
    { 0x003E, matter_cmd_003e_vals, matter_rsp_003e_vals, matter_attr_003e_vals },
    { 0x003F, matter_cmd_003f_vals, matter_rsp_003f_vals, matter_attr_003f_vals },
    { 0x0040, NULL, NULL, matter_attr_0040_vals },
    { 0x0041, NULL, NULL, matter_attr_0041_vals },
    { 0x0045, NULL, NULL, matter_attr_0045_vals },
    { 0x0046, matter_cmd_0046_vals, matter_rsp_0046_vals, matter_attr_0046_vals },
    { 0x0049, NULL, NULL, matter_attr_0049_vals },
    { 0x004A, NULL, NULL, matter_attr_004a_vals },
    { 0x0050, matter_cmd_0050_vals, NULL, matter_attr_0050_vals },
    { 0x0051, NULL, NULL, matter_attr_0051_vals },
    { 0x0052, NULL, NULL, matter_attr_0052_vals },
    { 0x0053, NULL, NULL, matter_attr_0053_vals },
    { 0x0054, NULL, NULL, matter_attr_0054_vals },
    { 0x0055, NULL, NULL, matter_attr_0055_vals },
    { 0x0056, matter_cmd_0056_vals, NULL, matter_attr_0056_vals },
    { 0x0059, NULL, NULL, matter_attr_0059_vals },
    { 0x005B, NULL, NULL, matter_attr_005b_vals },
    { 0x005C, matter_cmd_005c_vals, NULL, matter_attr_005c_vals },
    { 0x005E, NULL, NULL, matter_attr_005e_vals },
    { 0x005F, matter_cmd_005f_vals, NULL, matter_attr_005f_vals },
    { 0x0060, matter_cmd_0060_vals, matter_rsp_0060_vals, matter_attr_0060_vals },
    { 0x0061, matter_cmd_0061_vals, NULL, NULL },
    { 0x0062, matter_cmd_0062_vals, matter_rsp_0062_vals, matter_attr_0062_vals },
    { 0x0064, matter_cmd_0064_vals, NULL, matter_attr_0064_vals },
    { 0x0065, matter_cmd_0065_vals, matter_rsp_0065_vals, matter_attr_0065_vals },
    { 0x0071, matter_cmd_0071_vals, NULL, matter_attr_0071_vals },
    { 0x0072, matter_cmd_0072_vals, NULL, matter_attr_0072_vals },
    { 0x0079, matter_cmd_0079_vals, NULL, matter_attr_0079_vals },
    { 0x0080, matter_cmd_0080_vals, NULL, matter_attr_0080_vals },
    { 0x0081, matter_cmd_0081_vals, NULL, matter_attr_0081_vals },
    { 0x0090, NULL, NULL, matter_attr_0090_vals },
    { 0x0091, NULL, NULL, matter_attr_0091_vals },
    { 0x0094, matter_cmd_0094_vals, NULL, matter_attr_0094_vals },
    { 0x0095, matter_cmd_0095_vals, matter_rsp_0095_vals, matter_attr_0095_vals },
    { 0x0097, matter_cmd_0097_vals, NULL, matter_attr_0097_vals },
    { 0x0098, matter_cmd_0098_vals, NULL, matter_attr_0098_vals },
    { 0x0099, matter_cmd_0099_vals, matter_rsp_0099_vals, matter_attr_0099_vals },
    { 0x009B, NULL, NULL, matter_attr_009b_vals },
    { 0x009C, NULL, NULL, matter_attr_009c_vals },
    { 0x009D, NULL, NULL, matter_attr_009d_vals },
    { 0x009E, NULL, NULL, matter_attr_009e_vals },
    { 0x009F, NULL, NULL, matter_attr_009f_vals },
    { 0x00A0, NULL, NULL, matter_attr_00a0_vals },
    { 0x0101, matter_cmd_0101_vals, matter_rsp_0101_vals, matter_attr_0101_vals },
    { 0x0102, matter_cmd_0102_vals, NULL, matter_attr_0102_vals },
    { 0x0104, matter_cmd_0104_vals, NULL, matter_attr_0104_vals },
    { 0x0105, matter_cmd_0105_vals, NULL, matter_attr_0105_vals },
    { 0x0150, matter_cmd_0150_vals, matter_rsp_0150_vals, matter_attr_0150_vals },
    { 0x0200, NULL, NULL, matter_attr_0200_vals },
    { 0x0201, matter_cmd_0201_vals, matter_rsp_0201_vals, matter_attr_0201_vals },
    { 0x0202, matter_cmd_0202_vals, NULL, matter_attr_0202_vals },
    { 0x0204, NULL, NULL, matter_attr_0204_vals },
    { 0x0300, matter_cmd_0300_vals, NULL, matter_attr_0300_vals },
    { 0x0400, NULL, NULL, matter_attr_0400_vals },
    { 0x0402, NULL, NULL, matter_attr_0402_vals },
    { 0x0403, NULL, NULL, matter_attr_0403_vals },
    { 0x0404, NULL, NULL, matter_attr_0404_vals },
    { 0x0405, NULL, NULL, matter_attr_0405_vals },
    { 0x0406, NULL, NULL, matter_attr_0406_vals },
    { 0x040C, NULL, NULL, matter_attr_040c_vals },
    { 0x040D, NULL, NULL, matter_attr_040d_vals },
    { 0x0413, NULL, NULL, matter_attr_0413_vals },
    { 0x0415, NULL, NULL, matter_attr_0415_vals },
    { 0x042A, NULL, NULL, matter_attr_042a_vals },
    { 0x042B, NULL, NULL, matter_attr_042b_vals },
    { 0x042C, NULL, NULL, matter_attr_042c_vals },
    { 0x042D, NULL, NULL, matter_attr_042d_vals },
    { 0x042E, NULL, NULL, matter_attr_042e_vals },
    { 0x042F, NULL, NULL, matter_attr_042f_vals },
    { 0x0430, NULL, NULL, matter_attr_0430_vals },
    { 0x0431, NULL, NULL, matter_attr_0431_vals },
    { 0x0451, matter_cmd_0451_vals, matter_rsp_0451_vals, matter_attr_0451_vals },
    { 0x0452, matter_cmd_0452_vals, matter_rsp_0452_vals, matter_attr_0452_vals },
    { 0x0453, matter_cmd_0453_vals, matter_rsp_0453_vals, matter_attr_0453_vals },
    { 0x0503, NULL, NULL, matter_attr_0503_vals },
    { 0x0504, matter_cmd_0504_vals, matter_rsp_0504_vals, matter_attr_0504_vals },
    { 0x0505, matter_cmd_0505_vals, matter_rsp_0505_vals, matter_attr_0505_vals },
    { 0x0506, matter_cmd_0506_vals, matter_rsp_0506_vals, matter_attr_0506_vals },
    { 0x0507, matter_cmd_0507_vals, NULL, matter_attr_0507_vals },
    { 0x0508, matter_cmd_0508_vals, NULL, NULL },
    { 0x0509, matter_cmd_0509_vals, matter_rsp_0509_vals, NULL },
    { 0x050A, matter_cmd_050a_vals, matter_rsp_050a_vals, matter_attr_050a_vals },
    { 0x050B, matter_cmd_050b_vals, NULL, matter_attr_050b_vals },
    { 0x050C, matter_cmd_050c_vals, matter_rsp_050c_vals, matter_attr_050c_vals },
    { 0x050D, NULL, NULL, matter_attr_050d_vals },
    { 0x050E, matter_cmd_050e_vals, matter_rsp_050e_vals, NULL },
    { 0x050F, matter_cmd_050f_vals, matter_rsp_050f_vals, matter_attr_050f_vals },
    { 0x0510, matter_cmd_0510_vals, matter_rsp_0510_vals, NULL },
    { 0x0550, matter_cmd_0550_vals, matter_rsp_0550_vals, matter_attr_0550_vals },
    { 0x0551, matter_cmd_0551_vals, matter_rsp_0551_vals, matter_attr_0551_vals },
    { 0x0552, matter_cmd_0552_vals, NULL, matter_attr_0552_vals },
    { 0x0553, matter_cmd_0553_vals, matter_rsp_0553_vals, matter_attr_0553_vals },
    { 0x0554, matter_cmd_0554_vals, NULL, matter_attr_0554_vals },
    { 0x0555, matter_cmd_0555_vals, matter_rsp_0555_vals, matter_attr_0555_vals },
    { 0x0556, matter_cmd_0556_vals, NULL, matter_attr_0556_vals },
    { 0x0700, matter_cmd_0700_vals, matter_rsp_0700_vals, matter_attr_0700_vals },
    { 0x0750, NULL, NULL, matter_attr_0750_vals },
    { 0x0751, matter_cmd_0751_vals, matter_rsp_0751_vals, matter_attr_0751_vals },
    { 0x0752, matter_cmd_0752_vals, NULL, matter_attr_0752_vals },
    { 0x0753, matter_cmd_0753_vals, matter_rsp_0753_vals, matter_attr_0753_vals },
    { 0x0801, matter_cmd_0801_vals, matter_rsp_0801_vals, matter_attr_0801_vals },
    { 0x0802, matter_cmd_0802_vals, matter_rsp_0802_vals, matter_attr_0802_vals },
    { 0x0B06, NULL, NULL, matter_attr_0b06_vals },
    { 0x0B07, NULL, NULL, matter_attr_0b07_vals },
};

static const matter_cluster_members_t *
matter_cluster_lookup(uint32_t cluster_id)
{
    for (unsigned i = 0; i < array_length(matter_cluster_members); i++)
        if (matter_cluster_members[i].cluster_id == cluster_id)
            return &matter_cluster_members[i];
    return NULL;
}

const char *
matter_cluster_attribute_name(uint32_t cluster_id, uint32_t id)
{
    const matter_cluster_members_t *m = matter_cluster_lookup(cluster_id);
    return (m && m->attrs) ? try_val_to_str(id, m->attrs) : NULL;
}

const char *
matter_cluster_command_name(uint32_t cluster_id, uint32_t id, bool is_response)
{
    const matter_cluster_members_t *m = matter_cluster_lookup(cluster_id);
    if (!m)
        return NULL;
    const value_string *vs = is_response ? m->rsps : m->cmds;
    return vs ? try_val_to_str(id, vs) : NULL;
}
